// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/solarhell/certship/pkg/ent/appsettings"
)

// AppSettings is the model entity for the AppSettings schema.
type AppSettings struct {
	config `json:"-"`
	// ID of the ent.
	// 固定为 default，单行配置
	ID string `json:"id,omitempty"`
	// ACME 账号私钥 PEM，首次注册后写入
	AcmeAccountKey string `json:"acme_account_key,omitempty"`
	// ACME 注册信息 JSON，首次注册后写入
	AcmeRegistration string `json:"acme_registration,omitempty"`
	// 扫描间隔，Go duration 格式
	ScanInterval string `json:"scan_interval,omitempty"`
	// 域名连续多久未在云上扫到才判定为 missing,Go duration 格式
	MissingGrace string `json:"missing_grace,omitempty"`
	// 域名进入 missing 后再过多久归档并停止托管,Go duration 格式
	ArchiveAfter string `json:"archive_after,omitempty"`
	// 证书到期前多少天续期
	RenewBeforeDays int `json:"renew_before_days,omitempty"`
	// 归档且证书已过期的域名记录保留多久后物理删除,0s 表示永久保留
	ArchivedRetention string `json:"archived_retention,omitempty"`
	// 做 zone 探测与 DNS-01 校验时使用的递归 DNS,逗号分隔的 host:port
	DNSResolvers string `json:"dns_resolvers,omitempty"`
	// JWT 签名密钥，首次启动时自动生成
	JwtSecret string `json:"jwt_secret,omitempty"`
	// 更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AppSettings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case appsettings.FieldRenewBeforeDays:
			values[i] = new(sql.NullInt64)
		case appsettings.FieldID, appsettings.FieldAcmeAccountKey, appsettings.FieldAcmeRegistration, appsettings.FieldScanInterval, appsettings.FieldMissingGrace, appsettings.FieldArchiveAfter, appsettings.FieldArchivedRetention, appsettings.FieldDNSResolvers, appsettings.FieldJwtSecret:
			values[i] = new(sql.NullString)
		case appsettings.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AppSettings fields.
func (_m *AppSettings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case appsettings.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case appsettings.FieldAcmeAccountKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field acme_account_key", values[i])
			} else if value.Valid {
				_m.AcmeAccountKey = value.String
			}
		case appsettings.FieldAcmeRegistration:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field acme_registration", values[i])
			} else if value.Valid {
				_m.AcmeRegistration = value.String
			}
		case appsettings.FieldScanInterval:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scan_interval", values[i])
			} else if value.Valid {
				_m.ScanInterval = value.String
			}
		case appsettings.FieldMissingGrace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field missing_grace", values[i])
			} else if value.Valid {
				_m.MissingGrace = value.String
			}
		case appsettings.FieldArchiveAfter:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field archive_after", values[i])
			} else if value.Valid {
				_m.ArchiveAfter = value.String
			}
		case appsettings.FieldRenewBeforeDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field renew_before_days", values[i])
			} else if value.Valid {
				_m.RenewBeforeDays = int(value.Int64)
			}
		case appsettings.FieldArchivedRetention:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field archived_retention", values[i])
			} else if value.Valid {
				_m.ArchivedRetention = value.String
			}
		case appsettings.FieldDNSResolvers:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dns_resolvers", values[i])
			} else if value.Valid {
				_m.DNSResolvers = value.String
			}
		case appsettings.FieldJwtSecret:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field jwt_secret", values[i])
			} else if value.Valid {
				_m.JwtSecret = value.String
			}
		case appsettings.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AppSettings.
// This includes values selected through modifiers, order, etc.
func (_m *AppSettings) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AppSettings.
// Note that you need to call AppSettings.Unwrap() before calling this method if this AppSettings
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AppSettings) Update() *AppSettingsUpdateOne {
	return NewAppSettingsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AppSettings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AppSettings) Unwrap() *AppSettings {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AppSettings is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AppSettings) String() string {
	var builder strings.Builder
	builder.WriteString("AppSettings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("acme_account_key=")
	builder.WriteString(_m.AcmeAccountKey)
	builder.WriteString(", ")
	builder.WriteString("acme_registration=")
	builder.WriteString(_m.AcmeRegistration)
	builder.WriteString(", ")
	builder.WriteString("scan_interval=")
	builder.WriteString(_m.ScanInterval)
	builder.WriteString(", ")
	builder.WriteString("missing_grace=")
	builder.WriteString(_m.MissingGrace)
	builder.WriteString(", ")
	builder.WriteString("archive_after=")
	builder.WriteString(_m.ArchiveAfter)
	builder.WriteString(", ")
	builder.WriteString("renew_before_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.RenewBeforeDays))
	builder.WriteString(", ")
	builder.WriteString("archived_retention=")
	builder.WriteString(_m.ArchivedRetention)
	builder.WriteString(", ")
	builder.WriteString("dns_resolvers=")
	builder.WriteString(_m.DNSResolvers)
	builder.WriteString(", ")
	builder.WriteString("jwt_secret=")
	builder.WriteString(_m.JwtSecret)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AppSettingsSlice is a parsable slice of AppSettings.
type AppSettingsSlice []*AppSettings
