// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solarhell/certship/pkg/ent/appsettings"
)

// AppSettingsCreate is the builder for creating a AppSettings entity.
type AppSettingsCreate struct {
	config
	mutation *AppSettingsMutation
	hooks    []Hook
}

// SetAcmeAccountKey sets the "acme_account_key" field.
func (_c *AppSettingsCreate) SetAcmeAccountKey(v string) *AppSettingsCreate {
	_c.mutation.SetAcmeAccountKey(v)
	return _c
}

// SetNillableAcmeAccountKey sets the "acme_account_key" field if the given value is not nil.
func (_c *AppSettingsCreate) SetNillableAcmeAccountKey(v *string) *AppSettingsCreate {
	if v != nil {
		_c.SetAcmeAccountKey(*v)
	}
	return _c
}

// SetAcmeRegistration sets the "acme_registration" field.
func (_c *AppSettingsCreate) SetAcmeRegistration(v string) *AppSettingsCreate {
	_c.mutation.SetAcmeRegistration(v)
	return _c
}

// SetNillableAcmeRegistration sets the "acme_registration" field if the given value is not nil.
func (_c *AppSettingsCreate) SetNillableAcmeRegistration(v *string) *AppSettingsCreate {
	if v != nil {
		_c.SetAcmeRegistration(*v)
	}
	return _c
}

// SetScanInterval sets the "scan_interval" field.
func (_c *AppSettingsCreate) SetScanInterval(v string) *AppSettingsCreate {
	_c.mutation.SetScanInterval(v)
	return _c
}

// SetNillableScanInterval sets the "scan_interval" field if the given value is not nil.
func (_c *AppSettingsCreate) SetNillableScanInterval(v *string) *AppSettingsCreate {
	if v != nil {
		_c.SetScanInterval(*v)
	}
	return _c
}

// SetMissingGrace sets the "missing_grace" field.
func (_c *AppSettingsCreate) SetMissingGrace(v string) *AppSettingsCreate {
	_c.mutation.SetMissingGrace(v)
	return _c
}

// SetNillableMissingGrace sets the "missing_grace" field if the given value is not nil.
func (_c *AppSettingsCreate) SetNillableMissingGrace(v *string) *AppSettingsCreate {
	if v != nil {
		_c.SetMissingGrace(*v)
	}
	return _c
}

// SetArchiveAfter sets the "archive_after" field.
func (_c *AppSettingsCreate) SetArchiveAfter(v string) *AppSettingsCreate {
	_c.mutation.SetArchiveAfter(v)
	return _c
}

// SetNillableArchiveAfter sets the "archive_after" field if the given value is not nil.
func (_c *AppSettingsCreate) SetNillableArchiveAfter(v *string) *AppSettingsCreate {
	if v != nil {
		_c.SetArchiveAfter(*v)
	}
	return _c
}

// SetRenewBeforeDays sets the "renew_before_days" field.
func (_c *AppSettingsCreate) SetRenewBeforeDays(v int) *AppSettingsCreate {
	_c.mutation.SetRenewBeforeDays(v)
	return _c
}

// SetNillableRenewBeforeDays sets the "renew_before_days" field if the given value is not nil.
func (_c *AppSettingsCreate) SetNillableRenewBeforeDays(v *int) *AppSettingsCreate {
	if v != nil {
		_c.SetRenewBeforeDays(*v)
	}
	return _c
}

// SetArchivedRetention sets the "archived_retention" field.
func (_c *AppSettingsCreate) SetArchivedRetention(v string) *AppSettingsCreate {
	_c.mutation.SetArchivedRetention(v)
	return _c
}

// SetNillableArchivedRetention sets the "archived_retention" field if the given value is not nil.
func (_c *AppSettingsCreate) SetNillableArchivedRetention(v *string) *AppSettingsCreate {
	if v != nil {
		_c.SetArchivedRetention(*v)
	}
	return _c
}

// SetDNSResolvers sets the "dns_resolvers" field.
func (_c *AppSettingsCreate) SetDNSResolvers(v string) *AppSettingsCreate {
	_c.mutation.SetDNSResolvers(v)
	return _c
}

// SetNillableDNSResolvers sets the "dns_resolvers" field if the given value is not nil.
func (_c *AppSettingsCreate) SetNillableDNSResolvers(v *string) *AppSettingsCreate {
	if v != nil {
		_c.SetDNSResolvers(*v)
	}
	return _c
}

// SetJwtSecret sets the "jwt_secret" field.
func (_c *AppSettingsCreate) SetJwtSecret(v string) *AppSettingsCreate {
	_c.mutation.SetJwtSecret(v)
	return _c
}

// SetNillableJwtSecret sets the "jwt_secret" field if the given value is not nil.
func (_c *AppSettingsCreate) SetNillableJwtSecret(v *string) *AppSettingsCreate {
	if v != nil {
		_c.SetJwtSecret(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AppSettingsCreate) SetUpdatedAt(v time.Time) *AppSettingsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AppSettingsCreate) SetNillableUpdatedAt(v *time.Time) *AppSettingsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AppSettingsCreate) SetID(v string) *AppSettingsCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AppSettingsMutation object of the builder.
func (_c *AppSettingsCreate) Mutation() *AppSettingsMutation {
	return _c.mutation
}

// Save creates the AppSettings in the database.
func (_c *AppSettingsCreate) Save(ctx context.Context) (*AppSettings, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppSettingsCreate) SaveX(ctx context.Context) *AppSettings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppSettingsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppSettingsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppSettingsCreate) defaults() {
	if _, ok := _c.mutation.ScanInterval(); !ok {
		v := appsettings.DefaultScanInterval
		_c.mutation.SetScanInterval(v)
	}
	if _, ok := _c.mutation.MissingGrace(); !ok {
		v := appsettings.DefaultMissingGrace
		_c.mutation.SetMissingGrace(v)
	}
	if _, ok := _c.mutation.ArchiveAfter(); !ok {
		v := appsettings.DefaultArchiveAfter
		_c.mutation.SetArchiveAfter(v)
	}
	if _, ok := _c.mutation.RenewBeforeDays(); !ok {
		v := appsettings.DefaultRenewBeforeDays
		_c.mutation.SetRenewBeforeDays(v)
	}
	if _, ok := _c.mutation.ArchivedRetention(); !ok {
		v := appsettings.DefaultArchivedRetention
		_c.mutation.SetArchivedRetention(v)
	}
	if _, ok := _c.mutation.DNSResolvers(); !ok {
		v := appsettings.DefaultDNSResolvers
		_c.mutation.SetDNSResolvers(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := appsettings.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppSettingsCreate) check() error {
	if _, ok := _c.mutation.ScanInterval(); !ok {
		return &ValidationError{Name: "scan_interval", err: errors.New(`ent: missing required field "AppSettings.scan_interval"`)}
	}
	if v, ok := _c.mutation.ScanInterval(); ok {
		if err := appsettings.ScanIntervalValidator(v); err != nil {
			return &ValidationError{Name: "scan_interval", err: fmt.Errorf(`ent: validator failed for field "AppSettings.scan_interval": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MissingGrace(); !ok {
		return &ValidationError{Name: "missing_grace", err: errors.New(`ent: missing required field "AppSettings.missing_grace"`)}
	}
	if v, ok := _c.mutation.MissingGrace(); ok {
		if err := appsettings.MissingGraceValidator(v); err != nil {
			return &ValidationError{Name: "missing_grace", err: fmt.Errorf(`ent: validator failed for field "AppSettings.missing_grace": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ArchiveAfter(); !ok {
		return &ValidationError{Name: "archive_after", err: errors.New(`ent: missing required field "AppSettings.archive_after"`)}
	}
	if v, ok := _c.mutation.ArchiveAfter(); ok {
		if err := appsettings.ArchiveAfterValidator(v); err != nil {
			return &ValidationError{Name: "archive_after", err: fmt.Errorf(`ent: validator failed for field "AppSettings.archive_after": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RenewBeforeDays(); !ok {
		return &ValidationError{Name: "renew_before_days", err: errors.New(`ent: missing required field "AppSettings.renew_before_days"`)}
	}
	if v, ok := _c.mutation.RenewBeforeDays(); ok {
		if err := appsettings.RenewBeforeDaysValidator(v); err != nil {
			return &ValidationError{Name: "renew_before_days", err: fmt.Errorf(`ent: validator failed for field "AppSettings.renew_before_days": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ArchivedRetention(); !ok {
		return &ValidationError{Name: "archived_retention", err: errors.New(`ent: missing required field "AppSettings.archived_retention"`)}
	}
	if v, ok := _c.mutation.ArchivedRetention(); ok {
		if err := appsettings.ArchivedRetentionValidator(v); err != nil {
			return &ValidationError{Name: "archived_retention", err: fmt.Errorf(`ent: validator failed for field "AppSettings.archived_retention": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DNSResolvers(); !ok {
		return &ValidationError{Name: "dns_resolvers", err: errors.New(`ent: missing required field "AppSettings.dns_resolvers"`)}
	}
	if v, ok := _c.mutation.DNSResolvers(); ok {
		if err := appsettings.DNSResolversValidator(v); err != nil {
			return &ValidationError{Name: "dns_resolvers", err: fmt.Errorf(`ent: validator failed for field "AppSettings.dns_resolvers": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AppSettings.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := appsettings.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AppSettings.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AppSettingsCreate) sqlSave(ctx context.Context) (*AppSettings, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AppSettings.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppSettingsCreate) createSpec() (*AppSettings, *sqlgraph.CreateSpec) {
	var (
		_node = &AppSettings{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(appsettings.Table, sqlgraph.NewFieldSpec(appsettings.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AcmeAccountKey(); ok {
		_spec.SetField(appsettings.FieldAcmeAccountKey, field.TypeString, value)
		_node.AcmeAccountKey = value
	}
	if value, ok := _c.mutation.AcmeRegistration(); ok {
		_spec.SetField(appsettings.FieldAcmeRegistration, field.TypeString, value)
		_node.AcmeRegistration = value
	}
	if value, ok := _c.mutation.ScanInterval(); ok {
		_spec.SetField(appsettings.FieldScanInterval, field.TypeString, value)
		_node.ScanInterval = value
	}
	if value, ok := _c.mutation.MissingGrace(); ok {
		_spec.SetField(appsettings.FieldMissingGrace, field.TypeString, value)
		_node.MissingGrace = value
	}
	if value, ok := _c.mutation.ArchiveAfter(); ok {
		_spec.SetField(appsettings.FieldArchiveAfter, field.TypeString, value)
		_node.ArchiveAfter = value
	}
	if value, ok := _c.mutation.RenewBeforeDays(); ok {
		_spec.SetField(appsettings.FieldRenewBeforeDays, field.TypeInt, value)
		_node.RenewBeforeDays = value
	}
	if value, ok := _c.mutation.ArchivedRetention(); ok {
		_spec.SetField(appsettings.FieldArchivedRetention, field.TypeString, value)
		_node.ArchivedRetention = value
	}
	if value, ok := _c.mutation.DNSResolvers(); ok {
		_spec.SetField(appsettings.FieldDNSResolvers, field.TypeString, value)
		_node.DNSResolvers = value
	}
	if value, ok := _c.mutation.JwtSecret(); ok {
		_spec.SetField(appsettings.FieldJwtSecret, field.TypeString, value)
		_node.JwtSecret = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(appsettings.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AppSettingsCreateBulk is the builder for creating many AppSettings entities in bulk.
type AppSettingsCreateBulk struct {
	config
	err      error
	builders []*AppSettingsCreate
}

// Save creates the AppSettings entities in the database.
func (_c *AppSettingsCreateBulk) Save(ctx context.Context) ([]*AppSettings, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AppSettings, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppSettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppSettingsCreateBulk) SaveX(ctx context.Context) []*AppSettings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppSettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppSettingsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
