// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solarhell/certship/pkg/ent/appsettings"
	"github.com/solarhell/certship/pkg/ent/predicate"
)

// AppSettingsUpdate is the builder for updating AppSettings entities.
type AppSettingsUpdate struct {
	config
	hooks    []Hook
	mutation *AppSettingsMutation
}

// Where appends a list predicates to the AppSettingsUpdate builder.
func (_u *AppSettingsUpdate) Where(ps ...predicate.AppSettings) *AppSettingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAcmeEmail sets the "acme_email" field.
func (_u *AppSettingsUpdate) SetAcmeEmail(v string) *AppSettingsUpdate {
	_u.mutation.SetAcmeEmail(v)
	return _u
}

// SetNillableAcmeEmail sets the "acme_email" field if the given value is not nil.
func (_u *AppSettingsUpdate) SetNillableAcmeEmail(v *string) *AppSettingsUpdate {
	if v != nil {
		_u.SetAcmeEmail(*v)
	}
	return _u
}

// SetAcmeDirectoryURL sets the "acme_directory_url" field.
func (_u *AppSettingsUpdate) SetAcmeDirectoryURL(v string) *AppSettingsUpdate {
	_u.mutation.SetAcmeDirectoryURL(v)
	return _u
}

// SetNillableAcmeDirectoryURL sets the "acme_directory_url" field if the given value is not nil.
func (_u *AppSettingsUpdate) SetNillableAcmeDirectoryURL(v *string) *AppSettingsUpdate {
	if v != nil {
		_u.SetAcmeDirectoryURL(*v)
	}
	return _u
}

// SetAcmeAccountKey sets the "acme_account_key" field.
func (_u *AppSettingsUpdate) SetAcmeAccountKey(v string) *AppSettingsUpdate {
	_u.mutation.SetAcmeAccountKey(v)
	return _u
}

// SetNillableAcmeAccountKey sets the "acme_account_key" field if the given value is not nil.
func (_u *AppSettingsUpdate) SetNillableAcmeAccountKey(v *string) *AppSettingsUpdate {
	if v != nil {
		_u.SetAcmeAccountKey(*v)
	}
	return _u
}

// ClearAcmeAccountKey clears the value of the "acme_account_key" field.
func (_u *AppSettingsUpdate) ClearAcmeAccountKey() *AppSettingsUpdate {
	_u.mutation.ClearAcmeAccountKey()
	return _u
}

// SetAcmeRegistration sets the "acme_registration" field.
func (_u *AppSettingsUpdate) SetAcmeRegistration(v string) *AppSettingsUpdate {
	_u.mutation.SetAcmeRegistration(v)
	return _u
}

// SetNillableAcmeRegistration sets the "acme_registration" field if the given value is not nil.
func (_u *AppSettingsUpdate) SetNillableAcmeRegistration(v *string) *AppSettingsUpdate {
	if v != nil {
		_u.SetAcmeRegistration(*v)
	}
	return _u
}

// ClearAcmeRegistration clears the value of the "acme_registration" field.
func (_u *AppSettingsUpdate) ClearAcmeRegistration() *AppSettingsUpdate {
	_u.mutation.ClearAcmeRegistration()
	return _u
}

// SetScanInterval sets the "scan_interval" field.
func (_u *AppSettingsUpdate) SetScanInterval(v string) *AppSettingsUpdate {
	_u.mutation.SetScanInterval(v)
	return _u
}

// SetNillableScanInterval sets the "scan_interval" field if the given value is not nil.
func (_u *AppSettingsUpdate) SetNillableScanInterval(v *string) *AppSettingsUpdate {
	if v != nil {
		_u.SetScanInterval(*v)
	}
	return _u
}

// SetRenewBeforeDays sets the "renew_before_days" field.
func (_u *AppSettingsUpdate) SetRenewBeforeDays(v int) *AppSettingsUpdate {
	_u.mutation.ResetRenewBeforeDays()
	_u.mutation.SetRenewBeforeDays(v)
	return _u
}

// SetNillableRenewBeforeDays sets the "renew_before_days" field if the given value is not nil.
func (_u *AppSettingsUpdate) SetNillableRenewBeforeDays(v *int) *AppSettingsUpdate {
	if v != nil {
		_u.SetRenewBeforeDays(*v)
	}
	return _u
}

// AddRenewBeforeDays adds value to the "renew_before_days" field.
func (_u *AppSettingsUpdate) AddRenewBeforeDays(v int) *AppSettingsUpdate {
	_u.mutation.AddRenewBeforeDays(v)
	return _u
}

// SetJwtSecret sets the "jwt_secret" field.
func (_u *AppSettingsUpdate) SetJwtSecret(v string) *AppSettingsUpdate {
	_u.mutation.SetJwtSecret(v)
	return _u
}

// SetNillableJwtSecret sets the "jwt_secret" field if the given value is not nil.
func (_u *AppSettingsUpdate) SetNillableJwtSecret(v *string) *AppSettingsUpdate {
	if v != nil {
		_u.SetJwtSecret(*v)
	}
	return _u
}

// ClearJwtSecret clears the value of the "jwt_secret" field.
func (_u *AppSettingsUpdate) ClearJwtSecret() *AppSettingsUpdate {
	_u.mutation.ClearJwtSecret()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppSettingsUpdate) SetUpdatedAt(v time.Time) *AppSettingsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AppSettingsMutation object of the builder.
func (_u *AppSettingsUpdate) Mutation() *AppSettingsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppSettingsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppSettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppSettingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppSettingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppSettingsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := appsettings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppSettingsUpdate) check() error {
	if v, ok := _u.mutation.AcmeEmail(); ok {
		if err := appsettings.AcmeEmailValidator(v); err != nil {
			return &ValidationError{Name: "acme_email", err: fmt.Errorf(`ent: validator failed for field "AppSettings.acme_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AcmeDirectoryURL(); ok {
		if err := appsettings.AcmeDirectoryURLValidator(v); err != nil {
			return &ValidationError{Name: "acme_directory_url", err: fmt.Errorf(`ent: validator failed for field "AppSettings.acme_directory_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScanInterval(); ok {
		if err := appsettings.ScanIntervalValidator(v); err != nil {
			return &ValidationError{Name: "scan_interval", err: fmt.Errorf(`ent: validator failed for field "AppSettings.scan_interval": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RenewBeforeDays(); ok {
		if err := appsettings.RenewBeforeDaysValidator(v); err != nil {
			return &ValidationError{Name: "renew_before_days", err: fmt.Errorf(`ent: validator failed for field "AppSettings.renew_before_days": %w`, err)}
		}
	}
	return nil
}

func (_u *AppSettingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(appsettings.Table, appsettings.Columns, sqlgraph.NewFieldSpec(appsettings.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AcmeEmail(); ok {
		_spec.SetField(appsettings.FieldAcmeEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.AcmeDirectoryURL(); ok {
		_spec.SetField(appsettings.FieldAcmeDirectoryURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.AcmeAccountKey(); ok {
		_spec.SetField(appsettings.FieldAcmeAccountKey, field.TypeString, value)
	}
	if _u.mutation.AcmeAccountKeyCleared() {
		_spec.ClearField(appsettings.FieldAcmeAccountKey, field.TypeString)
	}
	if value, ok := _u.mutation.AcmeRegistration(); ok {
		_spec.SetField(appsettings.FieldAcmeRegistration, field.TypeString, value)
	}
	if _u.mutation.AcmeRegistrationCleared() {
		_spec.ClearField(appsettings.FieldAcmeRegistration, field.TypeString)
	}
	if value, ok := _u.mutation.ScanInterval(); ok {
		_spec.SetField(appsettings.FieldScanInterval, field.TypeString, value)
	}
	if value, ok := _u.mutation.RenewBeforeDays(); ok {
		_spec.SetField(appsettings.FieldRenewBeforeDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRenewBeforeDays(); ok {
		_spec.AddField(appsettings.FieldRenewBeforeDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.JwtSecret(); ok {
		_spec.SetField(appsettings.FieldJwtSecret, field.TypeString, value)
	}
	if _u.mutation.JwtSecretCleared() {
		_spec.ClearField(appsettings.FieldJwtSecret, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(appsettings.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppSettingsUpdateOne is the builder for updating a single AppSettings entity.
type AppSettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppSettingsMutation
}

// SetAcmeEmail sets the "acme_email" field.
func (_u *AppSettingsUpdateOne) SetAcmeEmail(v string) *AppSettingsUpdateOne {
	_u.mutation.SetAcmeEmail(v)
	return _u
}

// SetNillableAcmeEmail sets the "acme_email" field if the given value is not nil.
func (_u *AppSettingsUpdateOne) SetNillableAcmeEmail(v *string) *AppSettingsUpdateOne {
	if v != nil {
		_u.SetAcmeEmail(*v)
	}
	return _u
}

// SetAcmeDirectoryURL sets the "acme_directory_url" field.
func (_u *AppSettingsUpdateOne) SetAcmeDirectoryURL(v string) *AppSettingsUpdateOne {
	_u.mutation.SetAcmeDirectoryURL(v)
	return _u
}

// SetNillableAcmeDirectoryURL sets the "acme_directory_url" field if the given value is not nil.
func (_u *AppSettingsUpdateOne) SetNillableAcmeDirectoryURL(v *string) *AppSettingsUpdateOne {
	if v != nil {
		_u.SetAcmeDirectoryURL(*v)
	}
	return _u
}

// SetAcmeAccountKey sets the "acme_account_key" field.
func (_u *AppSettingsUpdateOne) SetAcmeAccountKey(v string) *AppSettingsUpdateOne {
	_u.mutation.SetAcmeAccountKey(v)
	return _u
}

// SetNillableAcmeAccountKey sets the "acme_account_key" field if the given value is not nil.
func (_u *AppSettingsUpdateOne) SetNillableAcmeAccountKey(v *string) *AppSettingsUpdateOne {
	if v != nil {
		_u.SetAcmeAccountKey(*v)
	}
	return _u
}

// ClearAcmeAccountKey clears the value of the "acme_account_key" field.
func (_u *AppSettingsUpdateOne) ClearAcmeAccountKey() *AppSettingsUpdateOne {
	_u.mutation.ClearAcmeAccountKey()
	return _u
}

// SetAcmeRegistration sets the "acme_registration" field.
func (_u *AppSettingsUpdateOne) SetAcmeRegistration(v string) *AppSettingsUpdateOne {
	_u.mutation.SetAcmeRegistration(v)
	return _u
}

// SetNillableAcmeRegistration sets the "acme_registration" field if the given value is not nil.
func (_u *AppSettingsUpdateOne) SetNillableAcmeRegistration(v *string) *AppSettingsUpdateOne {
	if v != nil {
		_u.SetAcmeRegistration(*v)
	}
	return _u
}

// ClearAcmeRegistration clears the value of the "acme_registration" field.
func (_u *AppSettingsUpdateOne) ClearAcmeRegistration() *AppSettingsUpdateOne {
	_u.mutation.ClearAcmeRegistration()
	return _u
}

// SetScanInterval sets the "scan_interval" field.
func (_u *AppSettingsUpdateOne) SetScanInterval(v string) *AppSettingsUpdateOne {
	_u.mutation.SetScanInterval(v)
	return _u
}

// SetNillableScanInterval sets the "scan_interval" field if the given value is not nil.
func (_u *AppSettingsUpdateOne) SetNillableScanInterval(v *string) *AppSettingsUpdateOne {
	if v != nil {
		_u.SetScanInterval(*v)
	}
	return _u
}

// SetRenewBeforeDays sets the "renew_before_days" field.
func (_u *AppSettingsUpdateOne) SetRenewBeforeDays(v int) *AppSettingsUpdateOne {
	_u.mutation.ResetRenewBeforeDays()
	_u.mutation.SetRenewBeforeDays(v)
	return _u
}

// SetNillableRenewBeforeDays sets the "renew_before_days" field if the given value is not nil.
func (_u *AppSettingsUpdateOne) SetNillableRenewBeforeDays(v *int) *AppSettingsUpdateOne {
	if v != nil {
		_u.SetRenewBeforeDays(*v)
	}
	return _u
}

// AddRenewBeforeDays adds value to the "renew_before_days" field.
func (_u *AppSettingsUpdateOne) AddRenewBeforeDays(v int) *AppSettingsUpdateOne {
	_u.mutation.AddRenewBeforeDays(v)
	return _u
}

// SetJwtSecret sets the "jwt_secret" field.
func (_u *AppSettingsUpdateOne) SetJwtSecret(v string) *AppSettingsUpdateOne {
	_u.mutation.SetJwtSecret(v)
	return _u
}

// SetNillableJwtSecret sets the "jwt_secret" field if the given value is not nil.
func (_u *AppSettingsUpdateOne) SetNillableJwtSecret(v *string) *AppSettingsUpdateOne {
	if v != nil {
		_u.SetJwtSecret(*v)
	}
	return _u
}

// ClearJwtSecret clears the value of the "jwt_secret" field.
func (_u *AppSettingsUpdateOne) ClearJwtSecret() *AppSettingsUpdateOne {
	_u.mutation.ClearJwtSecret()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppSettingsUpdateOne) SetUpdatedAt(v time.Time) *AppSettingsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AppSettingsMutation object of the builder.
func (_u *AppSettingsUpdateOne) Mutation() *AppSettingsMutation {
	return _u.mutation
}

// Where appends a list predicates to the AppSettingsUpdate builder.
func (_u *AppSettingsUpdateOne) Where(ps ...predicate.AppSettings) *AppSettingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppSettingsUpdateOne) Select(field string, fields ...string) *AppSettingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AppSettings entity.
func (_u *AppSettingsUpdateOne) Save(ctx context.Context) (*AppSettings, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppSettingsUpdateOne) SaveX(ctx context.Context) *AppSettings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppSettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppSettingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppSettingsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := appsettings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppSettingsUpdateOne) check() error {
	if v, ok := _u.mutation.AcmeEmail(); ok {
		if err := appsettings.AcmeEmailValidator(v); err != nil {
			return &ValidationError{Name: "acme_email", err: fmt.Errorf(`ent: validator failed for field "AppSettings.acme_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AcmeDirectoryURL(); ok {
		if err := appsettings.AcmeDirectoryURLValidator(v); err != nil {
			return &ValidationError{Name: "acme_directory_url", err: fmt.Errorf(`ent: validator failed for field "AppSettings.acme_directory_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScanInterval(); ok {
		if err := appsettings.ScanIntervalValidator(v); err != nil {
			return &ValidationError{Name: "scan_interval", err: fmt.Errorf(`ent: validator failed for field "AppSettings.scan_interval": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RenewBeforeDays(); ok {
		if err := appsettings.RenewBeforeDaysValidator(v); err != nil {
			return &ValidationError{Name: "renew_before_days", err: fmt.Errorf(`ent: validator failed for field "AppSettings.renew_before_days": %w`, err)}
		}
	}
	return nil
}

func (_u *AppSettingsUpdateOne) sqlSave(ctx context.Context) (_node *AppSettings, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(appsettings.Table, appsettings.Columns, sqlgraph.NewFieldSpec(appsettings.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppSettings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appsettings.FieldID)
		for _, f := range fields {
			if !appsettings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appsettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AcmeEmail(); ok {
		_spec.SetField(appsettings.FieldAcmeEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.AcmeDirectoryURL(); ok {
		_spec.SetField(appsettings.FieldAcmeDirectoryURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.AcmeAccountKey(); ok {
		_spec.SetField(appsettings.FieldAcmeAccountKey, field.TypeString, value)
	}
	if _u.mutation.AcmeAccountKeyCleared() {
		_spec.ClearField(appsettings.FieldAcmeAccountKey, field.TypeString)
	}
	if value, ok := _u.mutation.AcmeRegistration(); ok {
		_spec.SetField(appsettings.FieldAcmeRegistration, field.TypeString, value)
	}
	if _u.mutation.AcmeRegistrationCleared() {
		_spec.ClearField(appsettings.FieldAcmeRegistration, field.TypeString)
	}
	if value, ok := _u.mutation.ScanInterval(); ok {
		_spec.SetField(appsettings.FieldScanInterval, field.TypeString, value)
	}
	if value, ok := _u.mutation.RenewBeforeDays(); ok {
		_spec.SetField(appsettings.FieldRenewBeforeDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRenewBeforeDays(); ok {
		_spec.AddField(appsettings.FieldRenewBeforeDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.JwtSecret(); ok {
		_spec.SetField(appsettings.FieldJwtSecret, field.TypeString, value)
	}
	if _u.mutation.JwtSecretCleared() {
		_spec.ClearField(appsettings.FieldJwtSecret, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(appsettings.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AppSettings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
