// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solarhell/certship/pkg/ent/domain"
)

// DomainCreate is the builder for creating a Domain entity.
type DomainCreate struct {
	config
	mutation *DomainMutation
	hooks    []Hook
}

// SetDomain sets the "domain" field.
func (_c *DomainCreate) SetDomain(v string) *DomainCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetBucket sets the "bucket" field.
func (_c *DomainCreate) SetBucket(v string) *DomainCreate {
	_c.mutation.SetBucket(v)
	return _c
}

// SetRegion sets the "region" field.
func (_c *DomainCreate) SetRegion(v string) *DomainCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetAccountName sets the "account_name" field.
func (_c *DomainCreate) SetAccountName(v string) *DomainCreate {
	_c.mutation.SetAccountName(v)
	return _c
}

// SetIssuedAt sets the "issued_at" field.
func (_c *DomainCreate) SetIssuedAt(v time.Time) *DomainCreate {
	_c.mutation.SetIssuedAt(v)
	return _c
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_c *DomainCreate) SetNillableIssuedAt(v *time.Time) *DomainCreate {
	if v != nil {
		_c.SetIssuedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *DomainCreate) SetExpiresAt(v time.Time) *DomainCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *DomainCreate) SetNillableExpiresAt(v *time.Time) *DomainCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCertPem sets the "cert_pem" field.
func (_c *DomainCreate) SetCertPem(v string) *DomainCreate {
	_c.mutation.SetCertPem(v)
	return _c
}

// SetNillableCertPem sets the "cert_pem" field if the given value is not nil.
func (_c *DomainCreate) SetNillableCertPem(v *string) *DomainCreate {
	if v != nil {
		_c.SetCertPem(*v)
	}
	return _c
}

// SetKeyPem sets the "key_pem" field.
func (_c *DomainCreate) SetKeyPem(v string) *DomainCreate {
	_c.mutation.SetKeyPem(v)
	return _c
}

// SetNillableKeyPem sets the "key_pem" field if the given value is not nil.
func (_c *DomainCreate) SetNillableKeyPem(v *string) *DomainCreate {
	if v != nil {
		_c.SetKeyPem(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DomainCreate) SetStatus(v domain.Status) *DomainCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DomainCreate) SetNillableStatus(v *domain.Status) *DomainCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *DomainCreate) SetErrorMessage(v string) *DomainCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *DomainCreate) SetNillableErrorMessage(v *string) *DomainCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DomainCreate) SetCreatedAt(v time.Time) *DomainCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DomainCreate) SetNillableCreatedAt(v *time.Time) *DomainCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DomainCreate) SetUpdatedAt(v time.Time) *DomainCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DomainCreate) SetNillableUpdatedAt(v *time.Time) *DomainCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DomainCreate) SetID(v string) *DomainCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DomainCreate) SetNillableID(v *string) *DomainCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DomainMutation object of the builder.
func (_c *DomainCreate) Mutation() *DomainMutation {
	return _c.mutation
}

// Save creates the Domain in the database.
func (_c *DomainCreate) Save(ctx context.Context) (*Domain, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DomainCreate) SaveX(ctx context.Context) *Domain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DomainCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DomainCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DomainCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := domain.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := domain.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := domain.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := domain.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DomainCreate) check() error {
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "Domain.domain"`)}
	}
	if v, ok := _c.mutation.Domain(); ok {
		if err := domain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Domain.domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Bucket(); !ok {
		return &ValidationError{Name: "bucket", err: errors.New(`ent: missing required field "Domain.bucket"`)}
	}
	if v, ok := _c.mutation.Bucket(); ok {
		if err := domain.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "Domain.bucket": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "Domain.region"`)}
	}
	if v, ok := _c.mutation.Region(); ok {
		if err := domain.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "Domain.region": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountName(); !ok {
		return &ValidationError{Name: "account_name", err: errors.New(`ent: missing required field "Domain.account_name"`)}
	}
	if v, ok := _c.mutation.AccountName(); ok {
		if err := domain.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "account_name", err: fmt.Errorf(`ent: validator failed for field "Domain.account_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Domain.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := domain.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Domain.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Domain.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Domain.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := domain.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Domain.id": %w`, err)}
		}
	}
	return nil
}

func (_c *DomainCreate) sqlSave(ctx context.Context) (*Domain, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Domain.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DomainCreate) createSpec() (*Domain, *sqlgraph.CreateSpec) {
	var (
		_node = &Domain{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(domain.Table, sqlgraph.NewFieldSpec(domain.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(domain.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.Bucket(); ok {
		_spec.SetField(domain.FieldBucket, field.TypeString, value)
		_node.Bucket = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(domain.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.AccountName(); ok {
		_spec.SetField(domain.FieldAccountName, field.TypeString, value)
		_node.AccountName = value
	}
	if value, ok := _c.mutation.IssuedAt(); ok {
		_spec.SetField(domain.FieldIssuedAt, field.TypeTime, value)
		_node.IssuedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(domain.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.CertPem(); ok {
		_spec.SetField(domain.FieldCertPem, field.TypeString, value)
		_node.CertPem = value
	}
	if value, ok := _c.mutation.KeyPem(); ok {
		_spec.SetField(domain.FieldKeyPem, field.TypeString, value)
		_node.KeyPem = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(domain.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(domain.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(domain.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(domain.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DomainCreateBulk is the builder for creating many Domain entities in bulk.
type DomainCreateBulk struct {
	config
	err      error
	builders []*DomainCreate
}

// Save creates the Domain entities in the database.
func (_c *DomainCreateBulk) Save(ctx context.Context) ([]*Domain, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Domain, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DomainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DomainCreateBulk) SaveX(ctx context.Context) []*Domain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DomainCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DomainCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
