// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/solarhell/certship/pkg/ent/predicate"
	"github.com/solarhell/certship/pkg/ent/renewtask"
	"github.com/solarhell/certship/pkg/model"
)

// RenewTaskUpdate is the builder for updating RenewTask entities.
type RenewTaskUpdate struct {
	config
	hooks    []Hook
	mutation *RenewTaskMutation
}

// Where appends a list predicates to the RenewTaskUpdate builder.
func (_u *RenewTaskUpdate) Where(ps ...predicate.RenewTask) *RenewTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDomains sets the "domains" field.
func (_u *RenewTaskUpdate) SetDomains(v []string) *RenewTaskUpdate {
	_u.mutation.SetDomains(v)
	return _u
}

// AppendDomains appends value to the "domains" field.
func (_u *RenewTaskUpdate) AppendDomains(v []string) *RenewTaskUpdate {
	_u.mutation.AppendDomains(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RenewTaskUpdate) SetStatus(v renewtask.Status) *RenewTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RenewTaskUpdate) SetNillableStatus(v *renewtask.Status) *RenewTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *RenewTaskUpdate) SetTrigger(v renewtask.Trigger) *RenewTaskUpdate {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *RenewTaskUpdate) SetNillableTrigger(v *renewtask.Trigger) *RenewTaskUpdate {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetLog sets the "log" field.
func (_u *RenewTaskUpdate) SetLog(v []model.TaskLogEntry) *RenewTaskUpdate {
	_u.mutation.SetLog(v)
	return _u
}

// AppendLog appends value to the "log" field.
func (_u *RenewTaskUpdate) AppendLog(v []model.TaskLogEntry) *RenewTaskUpdate {
	_u.mutation.AppendLog(v)
	return _u
}

// ClearLog clears the value of the "log" field.
func (_u *RenewTaskUpdate) ClearLog() *RenewTaskUpdate {
	_u.mutation.ClearLog()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RenewTaskUpdate) SetErrorMessage(v string) *RenewTaskUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RenewTaskUpdate) SetNillableErrorMessage(v *string) *RenewTaskUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RenewTaskUpdate) ClearErrorMessage() *RenewTaskUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *RenewTaskUpdate) SetStartedAt(v time.Time) *RenewTaskUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *RenewTaskUpdate) SetNillableStartedAt(v *time.Time) *RenewTaskUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *RenewTaskUpdate) ClearStartedAt() *RenewTaskUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *RenewTaskUpdate) SetFinishedAt(v time.Time) *RenewTaskUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *RenewTaskUpdate) SetNillableFinishedAt(v *time.Time) *RenewTaskUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *RenewTaskUpdate) ClearFinishedAt() *RenewTaskUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the RenewTaskMutation object of the builder.
func (_u *RenewTaskUpdate) Mutation() *RenewTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RenewTaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RenewTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RenewTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RenewTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RenewTaskUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := renewtask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RenewTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Trigger(); ok {
		if err := renewtask.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "RenewTask.trigger": %w`, err)}
		}
	}
	return nil
}

func (_u *RenewTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(renewtask.Table, renewtask.Columns, sqlgraph.NewFieldSpec(renewtask.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Domains(); ok {
		_spec.SetField(renewtask.FieldDomains, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDomains(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, renewtask.FieldDomains, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(renewtask.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(renewtask.FieldTrigger, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Log(); ok {
		_spec.SetField(renewtask.FieldLog, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLog(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, renewtask.FieldLog, value)
		})
	}
	if _u.mutation.LogCleared() {
		_spec.ClearField(renewtask.FieldLog, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(renewtask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(renewtask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(renewtask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(renewtask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(renewtask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(renewtask.FieldFinishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{renewtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RenewTaskUpdateOne is the builder for updating a single RenewTask entity.
type RenewTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RenewTaskMutation
}

// SetDomains sets the "domains" field.
func (_u *RenewTaskUpdateOne) SetDomains(v []string) *RenewTaskUpdateOne {
	_u.mutation.SetDomains(v)
	return _u
}

// AppendDomains appends value to the "domains" field.
func (_u *RenewTaskUpdateOne) AppendDomains(v []string) *RenewTaskUpdateOne {
	_u.mutation.AppendDomains(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RenewTaskUpdateOne) SetStatus(v renewtask.Status) *RenewTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RenewTaskUpdateOne) SetNillableStatus(v *renewtask.Status) *RenewTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *RenewTaskUpdateOne) SetTrigger(v renewtask.Trigger) *RenewTaskUpdateOne {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *RenewTaskUpdateOne) SetNillableTrigger(v *renewtask.Trigger) *RenewTaskUpdateOne {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetLog sets the "log" field.
func (_u *RenewTaskUpdateOne) SetLog(v []model.TaskLogEntry) *RenewTaskUpdateOne {
	_u.mutation.SetLog(v)
	return _u
}

// AppendLog appends value to the "log" field.
func (_u *RenewTaskUpdateOne) AppendLog(v []model.TaskLogEntry) *RenewTaskUpdateOne {
	_u.mutation.AppendLog(v)
	return _u
}

// ClearLog clears the value of the "log" field.
func (_u *RenewTaskUpdateOne) ClearLog() *RenewTaskUpdateOne {
	_u.mutation.ClearLog()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RenewTaskUpdateOne) SetErrorMessage(v string) *RenewTaskUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RenewTaskUpdateOne) SetNillableErrorMessage(v *string) *RenewTaskUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RenewTaskUpdateOne) ClearErrorMessage() *RenewTaskUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *RenewTaskUpdateOne) SetStartedAt(v time.Time) *RenewTaskUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *RenewTaskUpdateOne) SetNillableStartedAt(v *time.Time) *RenewTaskUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *RenewTaskUpdateOne) ClearStartedAt() *RenewTaskUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *RenewTaskUpdateOne) SetFinishedAt(v time.Time) *RenewTaskUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *RenewTaskUpdateOne) SetNillableFinishedAt(v *time.Time) *RenewTaskUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *RenewTaskUpdateOne) ClearFinishedAt() *RenewTaskUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the RenewTaskMutation object of the builder.
func (_u *RenewTaskUpdateOne) Mutation() *RenewTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the RenewTaskUpdate builder.
func (_u *RenewTaskUpdateOne) Where(ps ...predicate.RenewTask) *RenewTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RenewTaskUpdateOne) Select(field string, fields ...string) *RenewTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RenewTask entity.
func (_u *RenewTaskUpdateOne) Save(ctx context.Context) (*RenewTask, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RenewTaskUpdateOne) SaveX(ctx context.Context) *RenewTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RenewTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RenewTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RenewTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := renewtask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RenewTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Trigger(); ok {
		if err := renewtask.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "RenewTask.trigger": %w`, err)}
		}
	}
	return nil
}

func (_u *RenewTaskUpdateOne) sqlSave(ctx context.Context) (_node *RenewTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(renewtask.Table, renewtask.Columns, sqlgraph.NewFieldSpec(renewtask.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RenewTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, renewtask.FieldID)
		for _, f := range fields {
			if !renewtask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != renewtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Domains(); ok {
		_spec.SetField(renewtask.FieldDomains, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDomains(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, renewtask.FieldDomains, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(renewtask.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(renewtask.FieldTrigger, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Log(); ok {
		_spec.SetField(renewtask.FieldLog, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLog(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, renewtask.FieldLog, value)
		})
	}
	if _u.mutation.LogCleared() {
		_spec.ClearField(renewtask.FieldLog, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(renewtask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(renewtask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(renewtask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(renewtask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(renewtask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(renewtask.FieldFinishedAt, field.TypeTime)
	}
	_node = &RenewTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{renewtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
