// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: certship/v1/app_settings.proto

package certshipv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAppSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppSettingsRequest) Reset() {
	*x = GetAppSettingsRequest{}
	mi := &file_certship_v1_app_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppSettingsRequest) ProtoMessage() {}

func (x *GetAppSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_app_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetAppSettingsRequest) Descriptor() ([]byte, []int) {
	return file_certship_v1_app_settings_proto_rawDescGZIP(), []int{0}
}

type GetAppSettingsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AcmeEmail        string                 `protobuf:"bytes,1,opt,name=acme_email,json=acmeEmail,proto3" json:"acme_email,omitempty"`
	AcmeDirectoryUrl string                 `protobuf:"bytes,2,opt,name=acme_directory_url,json=acmeDirectoryUrl,proto3" json:"acme_directory_url,omitempty"`
	ScanInterval     string                 `protobuf:"bytes,3,opt,name=scan_interval,json=scanInterval,proto3" json:"scan_interval,omitempty"`
	RenewBeforeDays  int32                  `protobuf:"varint,4,opt,name=renew_before_days,json=renewBeforeDays,proto3" json:"renew_before_days,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAppSettingsResponse) Reset() {
	*x = GetAppSettingsResponse{}
	mi := &file_certship_v1_app_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppSettingsResponse) ProtoMessage() {}

func (x *GetAppSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_app_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetAppSettingsResponse) Descriptor() ([]byte, []int) {
	return file_certship_v1_app_settings_proto_rawDescGZIP(), []int{1}
}

func (x *GetAppSettingsResponse) GetAcmeEmail() string {
	if x != nil {
		return x.AcmeEmail
	}
	return ""
}

func (x *GetAppSettingsResponse) GetAcmeDirectoryUrl() string {
	if x != nil {
		return x.AcmeDirectoryUrl
	}
	return ""
}

func (x *GetAppSettingsResponse) GetScanInterval() string {
	if x != nil {
		return x.ScanInterval
	}
	return ""
}

func (x *GetAppSettingsResponse) GetRenewBeforeDays() int32 {
	if x != nil {
		return x.RenewBeforeDays
	}
	return 0
}

type UpdateAppSettingsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AcmeEmail        string                 `protobuf:"bytes,1,opt,name=acme_email,json=acmeEmail,proto3" json:"acme_email,omitempty"`
	AcmeDirectoryUrl string                 `protobuf:"bytes,2,opt,name=acme_directory_url,json=acmeDirectoryUrl,proto3" json:"acme_directory_url,omitempty"`
	ScanInterval     string                 `protobuf:"bytes,3,opt,name=scan_interval,json=scanInterval,proto3" json:"scan_interval,omitempty"`
	RenewBeforeDays  int32                  `protobuf:"varint,4,opt,name=renew_before_days,json=renewBeforeDays,proto3" json:"renew_before_days,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateAppSettingsRequest) Reset() {
	*x = UpdateAppSettingsRequest{}
	mi := &file_certship_v1_app_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppSettingsRequest) ProtoMessage() {}

func (x *UpdateAppSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_app_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppSettingsRequest) Descriptor() ([]byte, []int) {
	return file_certship_v1_app_settings_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateAppSettingsRequest) GetAcmeEmail() string {
	if x != nil {
		return x.AcmeEmail
	}
	return ""
}

func (x *UpdateAppSettingsRequest) GetAcmeDirectoryUrl() string {
	if x != nil {
		return x.AcmeDirectoryUrl
	}
	return ""
}

func (x *UpdateAppSettingsRequest) GetScanInterval() string {
	if x != nil {
		return x.ScanInterval
	}
	return ""
}

func (x *UpdateAppSettingsRequest) GetRenewBeforeDays() int32 {
	if x != nil {
		return x.RenewBeforeDays
	}
	return 0
}

type UpdateAppSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppSettingsResponse) Reset() {
	*x = UpdateAppSettingsResponse{}
	mi := &file_certship_v1_app_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppSettingsResponse) ProtoMessage() {}

func (x *UpdateAppSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_app_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateAppSettingsResponse) Descriptor() ([]byte, []int) {
	return file_certship_v1_app_settings_proto_rawDescGZIP(), []int{3}
}

var File_certship_v1_app_settings_proto protoreflect.FileDescriptor

const file_certship_v1_app_settings_proto_rawDesc = "" +
	"\n" +
	"\x1ecertship/v1/app_settings.proto\x12\vcertship.v1\"\x17\n" +
	"\x15GetAppSettingsRequest\"\xb6\x01\n" +
	"\x16GetAppSettingsResponse\x12\x1d\n" +
	"\n" +
	"acme_email\x18\x01 \x01(\tR\tacmeEmail\x12,\n" +
	"\x12acme_directory_url\x18\x02 \x01(\tR\x10acmeDirectoryUrl\x12#\n" +
	"\rscan_interval\x18\x03 \x01(\tR\fscanInterval\x12*\n" +
	"\x11renew_before_days\x18\x04 \x01(\x05R\x0frenewBeforeDays\"\xb8\x01\n" +
	"\x18UpdateAppSettingsRequest\x12\x1d\n" +
	"\n" +
	"acme_email\x18\x01 \x01(\tR\tacmeEmail\x12,\n" +
	"\x12acme_directory_url\x18\x02 \x01(\tR\x10acmeDirectoryUrl\x12#\n" +
	"\rscan_interval\x18\x03 \x01(\tR\fscanInterval\x12*\n" +
	"\x11renew_before_days\x18\x04 \x01(\x05R\x0frenewBeforeDays\"\x1b\n" +
	"\x19UpdateAppSettingsResponse2\xd3\x01\n" +
	"\x12AppSettingsService\x12Y\n" +
	"\x0eGetAppSettings\x12\".certship.v1.GetAppSettingsRequest\x1a#.certship.v1.GetAppSettingsResponse\x12b\n" +
	"\x11UpdateAppSettings\x12%.certship.v1.UpdateAppSettingsRequest\x1a&.certship.v1.UpdateAppSettingsResponseB>Z<github.com/solarhell/certship/pkg/api/certship/v1;certshipv1b\x06proto3"

var (
	file_certship_v1_app_settings_proto_rawDescOnce sync.Once
	file_certship_v1_app_settings_proto_rawDescData []byte
)

func file_certship_v1_app_settings_proto_rawDescGZIP() []byte {
	file_certship_v1_app_settings_proto_rawDescOnce.Do(func() {
		file_certship_v1_app_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_certship_v1_app_settings_proto_rawDesc), len(file_certship_v1_app_settings_proto_rawDesc)))
	})
	return file_certship_v1_app_settings_proto_rawDescData
}

var file_certship_v1_app_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_certship_v1_app_settings_proto_goTypes = []any{
	(*GetAppSettingsRequest)(nil),     // 0: certship.v1.GetAppSettingsRequest
	(*GetAppSettingsResponse)(nil),    // 1: certship.v1.GetAppSettingsResponse
	(*UpdateAppSettingsRequest)(nil),  // 2: certship.v1.UpdateAppSettingsRequest
	(*UpdateAppSettingsResponse)(nil), // 3: certship.v1.UpdateAppSettingsResponse
}
var file_certship_v1_app_settings_proto_depIdxs = []int32{
	0, // 0: certship.v1.AppSettingsService.GetAppSettings:input_type -> certship.v1.GetAppSettingsRequest
	2, // 1: certship.v1.AppSettingsService.UpdateAppSettings:input_type -> certship.v1.UpdateAppSettingsRequest
	1, // 2: certship.v1.AppSettingsService.GetAppSettings:output_type -> certship.v1.GetAppSettingsResponse
	3, // 3: certship.v1.AppSettingsService.UpdateAppSettings:output_type -> certship.v1.UpdateAppSettingsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_certship_v1_app_settings_proto_init() }
func file_certship_v1_app_settings_proto_init() {
	if File_certship_v1_app_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_certship_v1_app_settings_proto_rawDesc), len(file_certship_v1_app_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_certship_v1_app_settings_proto_goTypes,
		DependencyIndexes: file_certship_v1_app_settings_proto_depIdxs,
		MessageInfos:      file_certship_v1_app_settings_proto_msgTypes,
	}.Build()
	File_certship_v1_app_settings_proto = out.File
	file_certship_v1_app_settings_proto_goTypes = nil
	file_certship_v1_app_settings_proto_depIdxs = nil
}
