// Code generated by ent, DO NOT EDIT.

package appsettings

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/solarhell/certship/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContainsFold(FieldID, id))
}

// AcmeAccountKey applies equality check predicate on the "acme_account_key" field. It's identical to AcmeAccountKeyEQ.
func AcmeAccountKey(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldAcmeAccountKey, v))
}

// AcmeRegistration applies equality check predicate on the "acme_registration" field. It's identical to AcmeRegistrationEQ.
func AcmeRegistration(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldAcmeRegistration, v))
}

// ScanInterval applies equality check predicate on the "scan_interval" field. It's identical to ScanIntervalEQ.
func ScanInterval(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldScanInterval, v))
}

// MissingGrace applies equality check predicate on the "missing_grace" field. It's identical to MissingGraceEQ.
func MissingGrace(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldMissingGrace, v))
}

// ArchiveAfter applies equality check predicate on the "archive_after" field. It's identical to ArchiveAfterEQ.
func ArchiveAfter(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldArchiveAfter, v))
}

// RenewBeforeDays applies equality check predicate on the "renew_before_days" field. It's identical to RenewBeforeDaysEQ.
func RenewBeforeDays(v int) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldRenewBeforeDays, v))
}

// ArchivedRetention applies equality check predicate on the "archived_retention" field. It's identical to ArchivedRetentionEQ.
func ArchivedRetention(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldArchivedRetention, v))
}

// DNSResolvers applies equality check predicate on the "dns_resolvers" field. It's identical to DNSResolversEQ.
func DNSResolvers(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldDNSResolvers, v))
}

// JwtSecret applies equality check predicate on the "jwt_secret" field. It's identical to JwtSecretEQ.
func JwtSecret(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldJwtSecret, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldUpdatedAt, v))
}

// AcmeAccountKeyEQ applies the EQ predicate on the "acme_account_key" field.
func AcmeAccountKeyEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldAcmeAccountKey, v))
}

// AcmeAccountKeyNEQ applies the NEQ predicate on the "acme_account_key" field.
func AcmeAccountKeyNEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNEQ(FieldAcmeAccountKey, v))
}

// AcmeAccountKeyIn applies the In predicate on the "acme_account_key" field.
func AcmeAccountKeyIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldIn(FieldAcmeAccountKey, vs...))
}

// AcmeAccountKeyNotIn applies the NotIn predicate on the "acme_account_key" field.
func AcmeAccountKeyNotIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNotIn(FieldAcmeAccountKey, vs...))
}

// AcmeAccountKeyGT applies the GT predicate on the "acme_account_key" field.
func AcmeAccountKeyGT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGT(FieldAcmeAccountKey, v))
}

// AcmeAccountKeyGTE applies the GTE predicate on the "acme_account_key" field.
func AcmeAccountKeyGTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGTE(FieldAcmeAccountKey, v))
}

// AcmeAccountKeyLT applies the LT predicate on the "acme_account_key" field.
func AcmeAccountKeyLT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLT(FieldAcmeAccountKey, v))
}

// AcmeAccountKeyLTE applies the LTE predicate on the "acme_account_key" field.
func AcmeAccountKeyLTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLTE(FieldAcmeAccountKey, v))
}

// AcmeAccountKeyContains applies the Contains predicate on the "acme_account_key" field.
func AcmeAccountKeyContains(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContains(FieldAcmeAccountKey, v))
}

// AcmeAccountKeyHasPrefix applies the HasPrefix predicate on the "acme_account_key" field.
func AcmeAccountKeyHasPrefix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasPrefix(FieldAcmeAccountKey, v))
}

// AcmeAccountKeyHasSuffix applies the HasSuffix predicate on the "acme_account_key" field.
func AcmeAccountKeyHasSuffix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasSuffix(FieldAcmeAccountKey, v))
}

// AcmeAccountKeyIsNil applies the IsNil predicate on the "acme_account_key" field.
func AcmeAccountKeyIsNil() predicate.AppSettings {
	return predicate.AppSettings(sql.FieldIsNull(FieldAcmeAccountKey))
}

// AcmeAccountKeyNotNil applies the NotNil predicate on the "acme_account_key" field.
func AcmeAccountKeyNotNil() predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNotNull(FieldAcmeAccountKey))
}

// AcmeAccountKeyEqualFold applies the EqualFold predicate on the "acme_account_key" field.
func AcmeAccountKeyEqualFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEqualFold(FieldAcmeAccountKey, v))
}

// AcmeAccountKeyContainsFold applies the ContainsFold predicate on the "acme_account_key" field.
func AcmeAccountKeyContainsFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContainsFold(FieldAcmeAccountKey, v))
}

// AcmeRegistrationEQ applies the EQ predicate on the "acme_registration" field.
func AcmeRegistrationEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldAcmeRegistration, v))
}

// AcmeRegistrationNEQ applies the NEQ predicate on the "acme_registration" field.
func AcmeRegistrationNEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNEQ(FieldAcmeRegistration, v))
}

// AcmeRegistrationIn applies the In predicate on the "acme_registration" field.
func AcmeRegistrationIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldIn(FieldAcmeRegistration, vs...))
}

// AcmeRegistrationNotIn applies the NotIn predicate on the "acme_registration" field.
func AcmeRegistrationNotIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNotIn(FieldAcmeRegistration, vs...))
}

// AcmeRegistrationGT applies the GT predicate on the "acme_registration" field.
func AcmeRegistrationGT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGT(FieldAcmeRegistration, v))
}

// AcmeRegistrationGTE applies the GTE predicate on the "acme_registration" field.
func AcmeRegistrationGTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGTE(FieldAcmeRegistration, v))
}

// AcmeRegistrationLT applies the LT predicate on the "acme_registration" field.
func AcmeRegistrationLT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLT(FieldAcmeRegistration, v))
}

// AcmeRegistrationLTE applies the LTE predicate on the "acme_registration" field.
func AcmeRegistrationLTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLTE(FieldAcmeRegistration, v))
}

// AcmeRegistrationContains applies the Contains predicate on the "acme_registration" field.
func AcmeRegistrationContains(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContains(FieldAcmeRegistration, v))
}

// AcmeRegistrationHasPrefix applies the HasPrefix predicate on the "acme_registration" field.
func AcmeRegistrationHasPrefix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasPrefix(FieldAcmeRegistration, v))
}

// AcmeRegistrationHasSuffix applies the HasSuffix predicate on the "acme_registration" field.
func AcmeRegistrationHasSuffix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasSuffix(FieldAcmeRegistration, v))
}

// AcmeRegistrationIsNil applies the IsNil predicate on the "acme_registration" field.
func AcmeRegistrationIsNil() predicate.AppSettings {
	return predicate.AppSettings(sql.FieldIsNull(FieldAcmeRegistration))
}

// AcmeRegistrationNotNil applies the NotNil predicate on the "acme_registration" field.
func AcmeRegistrationNotNil() predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNotNull(FieldAcmeRegistration))
}

// AcmeRegistrationEqualFold applies the EqualFold predicate on the "acme_registration" field.
func AcmeRegistrationEqualFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEqualFold(FieldAcmeRegistration, v))
}

// AcmeRegistrationContainsFold applies the ContainsFold predicate on the "acme_registration" field.
func AcmeRegistrationContainsFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContainsFold(FieldAcmeRegistration, v))
}

// ScanIntervalEQ applies the EQ predicate on the "scan_interval" field.
func ScanIntervalEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldScanInterval, v))
}

// ScanIntervalNEQ applies the NEQ predicate on the "scan_interval" field.
func ScanIntervalNEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNEQ(FieldScanInterval, v))
}

// ScanIntervalIn applies the In predicate on the "scan_interval" field.
func ScanIntervalIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldIn(FieldScanInterval, vs...))
}

// ScanIntervalNotIn applies the NotIn predicate on the "scan_interval" field.
func ScanIntervalNotIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNotIn(FieldScanInterval, vs...))
}

// ScanIntervalGT applies the GT predicate on the "scan_interval" field.
func ScanIntervalGT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGT(FieldScanInterval, v))
}

// ScanIntervalGTE applies the GTE predicate on the "scan_interval" field.
func ScanIntervalGTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGTE(FieldScanInterval, v))
}

// ScanIntervalLT applies the LT predicate on the "scan_interval" field.
func ScanIntervalLT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLT(FieldScanInterval, v))
}

// ScanIntervalLTE applies the LTE predicate on the "scan_interval" field.
func ScanIntervalLTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLTE(FieldScanInterval, v))
}

// ScanIntervalContains applies the Contains predicate on the "scan_interval" field.
func ScanIntervalContains(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContains(FieldScanInterval, v))
}

// ScanIntervalHasPrefix applies the HasPrefix predicate on the "scan_interval" field.
func ScanIntervalHasPrefix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasPrefix(FieldScanInterval, v))
}

// ScanIntervalHasSuffix applies the HasSuffix predicate on the "scan_interval" field.
func ScanIntervalHasSuffix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasSuffix(FieldScanInterval, v))
}

// ScanIntervalEqualFold applies the EqualFold predicate on the "scan_interval" field.
func ScanIntervalEqualFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEqualFold(FieldScanInterval, v))
}

// ScanIntervalContainsFold applies the ContainsFold predicate on the "scan_interval" field.
func ScanIntervalContainsFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContainsFold(FieldScanInterval, v))
}

// MissingGraceEQ applies the EQ predicate on the "missing_grace" field.
func MissingGraceEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldMissingGrace, v))
}

// MissingGraceNEQ applies the NEQ predicate on the "missing_grace" field.
func MissingGraceNEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNEQ(FieldMissingGrace, v))
}

// MissingGraceIn applies the In predicate on the "missing_grace" field.
func MissingGraceIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldIn(FieldMissingGrace, vs...))
}

// MissingGraceNotIn applies the NotIn predicate on the "missing_grace" field.
func MissingGraceNotIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNotIn(FieldMissingGrace, vs...))
}

// MissingGraceGT applies the GT predicate on the "missing_grace" field.
func MissingGraceGT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGT(FieldMissingGrace, v))
}

// MissingGraceGTE applies the GTE predicate on the "missing_grace" field.
func MissingGraceGTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGTE(FieldMissingGrace, v))
}

// MissingGraceLT applies the LT predicate on the "missing_grace" field.
func MissingGraceLT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLT(FieldMissingGrace, v))
}

// MissingGraceLTE applies the LTE predicate on the "missing_grace" field.
func MissingGraceLTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLTE(FieldMissingGrace, v))
}

// MissingGraceContains applies the Contains predicate on the "missing_grace" field.
func MissingGraceContains(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContains(FieldMissingGrace, v))
}

// MissingGraceHasPrefix applies the HasPrefix predicate on the "missing_grace" field.
func MissingGraceHasPrefix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasPrefix(FieldMissingGrace, v))
}

// MissingGraceHasSuffix applies the HasSuffix predicate on the "missing_grace" field.
func MissingGraceHasSuffix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasSuffix(FieldMissingGrace, v))
}

// MissingGraceEqualFold applies the EqualFold predicate on the "missing_grace" field.
func MissingGraceEqualFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEqualFold(FieldMissingGrace, v))
}

// MissingGraceContainsFold applies the ContainsFold predicate on the "missing_grace" field.
func MissingGraceContainsFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContainsFold(FieldMissingGrace, v))
}

// ArchiveAfterEQ applies the EQ predicate on the "archive_after" field.
func ArchiveAfterEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldArchiveAfter, v))
}

// ArchiveAfterNEQ applies the NEQ predicate on the "archive_after" field.
func ArchiveAfterNEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNEQ(FieldArchiveAfter, v))
}

// ArchiveAfterIn applies the In predicate on the "archive_after" field.
func ArchiveAfterIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldIn(FieldArchiveAfter, vs...))
}

// ArchiveAfterNotIn applies the NotIn predicate on the "archive_after" field.
func ArchiveAfterNotIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNotIn(FieldArchiveAfter, vs...))
}

// ArchiveAfterGT applies the GT predicate on the "archive_after" field.
func ArchiveAfterGT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGT(FieldArchiveAfter, v))
}

// ArchiveAfterGTE applies the GTE predicate on the "archive_after" field.
func ArchiveAfterGTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGTE(FieldArchiveAfter, v))
}

// ArchiveAfterLT applies the LT predicate on the "archive_after" field.
func ArchiveAfterLT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLT(FieldArchiveAfter, v))
}

// ArchiveAfterLTE applies the LTE predicate on the "archive_after" field.
func ArchiveAfterLTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLTE(FieldArchiveAfter, v))
}

// ArchiveAfterContains applies the Contains predicate on the "archive_after" field.
func ArchiveAfterContains(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContains(FieldArchiveAfter, v))
}

// ArchiveAfterHasPrefix applies the HasPrefix predicate on the "archive_after" field.
func ArchiveAfterHasPrefix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasPrefix(FieldArchiveAfter, v))
}

// ArchiveAfterHasSuffix applies the HasSuffix predicate on the "archive_after" field.
func ArchiveAfterHasSuffix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasSuffix(FieldArchiveAfter, v))
}

// ArchiveAfterEqualFold applies the EqualFold predicate on the "archive_after" field.
func ArchiveAfterEqualFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEqualFold(FieldArchiveAfter, v))
}

// ArchiveAfterContainsFold applies the ContainsFold predicate on the "archive_after" field.
func ArchiveAfterContainsFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContainsFold(FieldArchiveAfter, v))
}

// RenewBeforeDaysEQ applies the EQ predicate on the "renew_before_days" field.
func RenewBeforeDaysEQ(v int) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldRenewBeforeDays, v))
}

// RenewBeforeDaysNEQ applies the NEQ predicate on the "renew_before_days" field.
func RenewBeforeDaysNEQ(v int) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNEQ(FieldRenewBeforeDays, v))
}

// RenewBeforeDaysIn applies the In predicate on the "renew_before_days" field.
func RenewBeforeDaysIn(vs ...int) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldIn(FieldRenewBeforeDays, vs...))
}

// RenewBeforeDaysNotIn applies the NotIn predicate on the "renew_before_days" field.
func RenewBeforeDaysNotIn(vs ...int) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNotIn(FieldRenewBeforeDays, vs...))
}

// RenewBeforeDaysGT applies the GT predicate on the "renew_before_days" field.
func RenewBeforeDaysGT(v int) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGT(FieldRenewBeforeDays, v))
}

// RenewBeforeDaysGTE applies the GTE predicate on the "renew_before_days" field.
func RenewBeforeDaysGTE(v int) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGTE(FieldRenewBeforeDays, v))
}

// RenewBeforeDaysLT applies the LT predicate on the "renew_before_days" field.
func RenewBeforeDaysLT(v int) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLT(FieldRenewBeforeDays, v))
}

// RenewBeforeDaysLTE applies the LTE predicate on the "renew_before_days" field.
func RenewBeforeDaysLTE(v int) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLTE(FieldRenewBeforeDays, v))
}

// ArchivedRetentionEQ applies the EQ predicate on the "archived_retention" field.
func ArchivedRetentionEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldArchivedRetention, v))
}

// ArchivedRetentionNEQ applies the NEQ predicate on the "archived_retention" field.
func ArchivedRetentionNEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNEQ(FieldArchivedRetention, v))
}

// ArchivedRetentionIn applies the In predicate on the "archived_retention" field.
func ArchivedRetentionIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldIn(FieldArchivedRetention, vs...))
}

// ArchivedRetentionNotIn applies the NotIn predicate on the "archived_retention" field.
func ArchivedRetentionNotIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNotIn(FieldArchivedRetention, vs...))
}

// ArchivedRetentionGT applies the GT predicate on the "archived_retention" field.
func ArchivedRetentionGT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGT(FieldArchivedRetention, v))
}

// ArchivedRetentionGTE applies the GTE predicate on the "archived_retention" field.
func ArchivedRetentionGTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGTE(FieldArchivedRetention, v))
}

// ArchivedRetentionLT applies the LT predicate on the "archived_retention" field.
func ArchivedRetentionLT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLT(FieldArchivedRetention, v))
}

// ArchivedRetentionLTE applies the LTE predicate on the "archived_retention" field.
func ArchivedRetentionLTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLTE(FieldArchivedRetention, v))
}

// ArchivedRetentionContains applies the Contains predicate on the "archived_retention" field.
func ArchivedRetentionContains(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContains(FieldArchivedRetention, v))
}

// ArchivedRetentionHasPrefix applies the HasPrefix predicate on the "archived_retention" field.
func ArchivedRetentionHasPrefix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasPrefix(FieldArchivedRetention, v))
}

// ArchivedRetentionHasSuffix applies the HasSuffix predicate on the "archived_retention" field.
func ArchivedRetentionHasSuffix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasSuffix(FieldArchivedRetention, v))
}

// ArchivedRetentionEqualFold applies the EqualFold predicate on the "archived_retention" field.
func ArchivedRetentionEqualFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEqualFold(FieldArchivedRetention, v))
}

// ArchivedRetentionContainsFold applies the ContainsFold predicate on the "archived_retention" field.
func ArchivedRetentionContainsFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContainsFold(FieldArchivedRetention, v))
}

// DNSResolversEQ applies the EQ predicate on the "dns_resolvers" field.
func DNSResolversEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldDNSResolvers, v))
}

// DNSResolversNEQ applies the NEQ predicate on the "dns_resolvers" field.
func DNSResolversNEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNEQ(FieldDNSResolvers, v))
}

// DNSResolversIn applies the In predicate on the "dns_resolvers" field.
func DNSResolversIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldIn(FieldDNSResolvers, vs...))
}

// DNSResolversNotIn applies the NotIn predicate on the "dns_resolvers" field.
func DNSResolversNotIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNotIn(FieldDNSResolvers, vs...))
}

// DNSResolversGT applies the GT predicate on the "dns_resolvers" field.
func DNSResolversGT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGT(FieldDNSResolvers, v))
}

// DNSResolversGTE applies the GTE predicate on the "dns_resolvers" field.
func DNSResolversGTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGTE(FieldDNSResolvers, v))
}

// DNSResolversLT applies the LT predicate on the "dns_resolvers" field.
func DNSResolversLT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLT(FieldDNSResolvers, v))
}

// DNSResolversLTE applies the LTE predicate on the "dns_resolvers" field.
func DNSResolversLTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLTE(FieldDNSResolvers, v))
}

// DNSResolversContains applies the Contains predicate on the "dns_resolvers" field.
func DNSResolversContains(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContains(FieldDNSResolvers, v))
}

// DNSResolversHasPrefix applies the HasPrefix predicate on the "dns_resolvers" field.
func DNSResolversHasPrefix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasPrefix(FieldDNSResolvers, v))
}

// DNSResolversHasSuffix applies the HasSuffix predicate on the "dns_resolvers" field.
func DNSResolversHasSuffix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasSuffix(FieldDNSResolvers, v))
}

// DNSResolversEqualFold applies the EqualFold predicate on the "dns_resolvers" field.
func DNSResolversEqualFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEqualFold(FieldDNSResolvers, v))
}

// DNSResolversContainsFold applies the ContainsFold predicate on the "dns_resolvers" field.
func DNSResolversContainsFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContainsFold(FieldDNSResolvers, v))
}

// JwtSecretEQ applies the EQ predicate on the "jwt_secret" field.
func JwtSecretEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldJwtSecret, v))
}

// JwtSecretNEQ applies the NEQ predicate on the "jwt_secret" field.
func JwtSecretNEQ(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNEQ(FieldJwtSecret, v))
}

// JwtSecretIn applies the In predicate on the "jwt_secret" field.
func JwtSecretIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldIn(FieldJwtSecret, vs...))
}

// JwtSecretNotIn applies the NotIn predicate on the "jwt_secret" field.
func JwtSecretNotIn(vs ...string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNotIn(FieldJwtSecret, vs...))
}

// JwtSecretGT applies the GT predicate on the "jwt_secret" field.
func JwtSecretGT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGT(FieldJwtSecret, v))
}

// JwtSecretGTE applies the GTE predicate on the "jwt_secret" field.
func JwtSecretGTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGTE(FieldJwtSecret, v))
}

// JwtSecretLT applies the LT predicate on the "jwt_secret" field.
func JwtSecretLT(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLT(FieldJwtSecret, v))
}

// JwtSecretLTE applies the LTE predicate on the "jwt_secret" field.
func JwtSecretLTE(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLTE(FieldJwtSecret, v))
}

// JwtSecretContains applies the Contains predicate on the "jwt_secret" field.
func JwtSecretContains(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContains(FieldJwtSecret, v))
}

// JwtSecretHasPrefix applies the HasPrefix predicate on the "jwt_secret" field.
func JwtSecretHasPrefix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasPrefix(FieldJwtSecret, v))
}

// JwtSecretHasSuffix applies the HasSuffix predicate on the "jwt_secret" field.
func JwtSecretHasSuffix(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldHasSuffix(FieldJwtSecret, v))
}

// JwtSecretIsNil applies the IsNil predicate on the "jwt_secret" field.
func JwtSecretIsNil() predicate.AppSettings {
	return predicate.AppSettings(sql.FieldIsNull(FieldJwtSecret))
}

// JwtSecretNotNil applies the NotNil predicate on the "jwt_secret" field.
func JwtSecretNotNil() predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNotNull(FieldJwtSecret))
}

// JwtSecretEqualFold applies the EqualFold predicate on the "jwt_secret" field.
func JwtSecretEqualFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEqualFold(FieldJwtSecret, v))
}

// JwtSecretContainsFold applies the ContainsFold predicate on the "jwt_secret" field.
func JwtSecretContainsFold(v string) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldContainsFold(FieldJwtSecret, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AppSettings {
	return predicate.AppSettings(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppSettings) predicate.AppSettings {
	return predicate.AppSettings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppSettings) predicate.AppSettings {
	return predicate.AppSettings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppSettings) predicate.AppSettings {
	return predicate.AppSettings(sql.NotPredicates(p))
}
