// Code generated by ent, DO NOT EDIT.

package domain

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the domain type in the database.
	Label = "domain"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// FieldBucket holds the string denoting the bucket field in the database.
	FieldBucket = "bucket"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldAccountName holds the string denoting the account_name field in the database.
	FieldAccountName = "account_name"
	// FieldIssuedAt holds the string denoting the issued_at field in the database.
	FieldIssuedAt = "issued_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCertPem holds the string denoting the cert_pem field in the database.
	FieldCertPem = "cert_pem"
	// FieldKeyPem holds the string denoting the key_pem field in the database.
	FieldKeyPem = "key_pem"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDeployTarget holds the string denoting the deploy_target field in the database.
	FieldDeployTarget = "deploy_target"
	// FieldPresence holds the string denoting the presence field in the database.
	FieldPresence = "presence"
	// FieldOrigin holds the string denoting the origin field in the database.
	FieldOrigin = "origin"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldManaged holds the string denoting the managed field in the database.
	FieldManaged = "managed"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldNextRetryAt holds the string denoting the next_retry_at field in the database.
	FieldNextRetryAt = "next_retry_at"
	// FieldErrorKind holds the string denoting the error_kind field in the database.
	FieldErrorKind = "error_kind"
	// FieldNotifiedState holds the string denoting the notified_state field in the database.
	FieldNotifiedState = "notified_state"
	// FieldLastNotifiedAt holds the string denoting the last_notified_at field in the database.
	FieldLastNotifiedAt = "last_notified_at"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldBlockedReason holds the string denoting the blocked_reason field in the database.
	FieldBlockedReason = "blocked_reason"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the domain in the database.
	Table = "t_domain"
)

// Columns holds all SQL columns for domain fields.
var Columns = []string{
	FieldID,
	FieldDomain,
	FieldBucket,
	FieldRegion,
	FieldAccountName,
	FieldIssuedAt,
	FieldExpiresAt,
	FieldCertPem,
	FieldKeyPem,
	FieldStatus,
	FieldDeployTarget,
	FieldPresence,
	FieldOrigin,
	FieldLastSeenAt,
	FieldManaged,
	FieldRetryCount,
	FieldNextRetryAt,
	FieldErrorKind,
	FieldNotifiedState,
	FieldLastNotifiedAt,
	FieldErrorMessage,
	FieldBlockedReason,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	DomainValidator func(string) error
	// AccountNameValidator is a validator for the "account_name" field. It is called by the builders before save.
	AccountNameValidator func(string) error
	// DefaultManaged holds the default value on creation for the "managed" field.
	DefaultManaged bool
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int
	// RetryCountValidator is a validator for the "retry_count" field. It is called by the builders before save.
	RetryCountValidator func(int) error
	// DefaultBlockedReason holds the default value on creation for the "blocked_reason" field.
	DefaultBlockedReason string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending Status = "pending"
	StatusActive  Status = "active"
	StatusError   Status = "error"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusActive, StatusError:
		return nil
	default:
		return fmt.Errorf("domain: invalid enum value for status field: %q", s)
	}
}

// DeployTarget defines the type for the "deploy_target" enum field.
type DeployTarget string

// DeployTargetOss is the default value of the DeployTarget enum.
const DefaultDeployTarget = DeployTargetOss

// DeployTarget values.
const (
	DeployTargetOss DeployTarget = "oss"
	DeployTargetCdn DeployTarget = "cdn"
)

func (dt DeployTarget) String() string {
	return string(dt)
}

// DeployTargetValidator is a validator for the "deploy_target" field enum values. It is called by the builders before save.
func DeployTargetValidator(dt DeployTarget) error {
	switch dt {
	case DeployTargetOss, DeployTargetCdn:
		return nil
	default:
		return fmt.Errorf("domain: invalid enum value for deploy_target field: %q", dt)
	}
}

// Presence defines the type for the "presence" enum field.
type Presence string

// PresencePresent is the default value of the Presence enum.
const DefaultPresence = PresencePresent

// Presence values.
const (
	PresencePresent  Presence = "present"
	PresenceMissing  Presence = "missing"
	PresenceArchived Presence = "archived"
)

func (pr Presence) String() string {
	return string(pr)
}

// PresenceValidator is a validator for the "presence" field enum values. It is called by the builders before save.
func PresenceValidator(pr Presence) error {
	switch pr {
	case PresencePresent, PresenceMissing, PresenceArchived:
		return nil
	default:
		return fmt.Errorf("domain: invalid enum value for presence field: %q", pr)
	}
}

// Origin defines the type for the "origin" enum field.
type Origin string

// OriginOss is the default value of the Origin enum.
const DefaultOrigin = OriginOss

// Origin values.
const (
	OriginOss  Origin = "oss"
	OriginCdn  Origin = "cdn"
	OriginBoth Origin = "both"
)

func (o Origin) String() string {
	return string(o)
}

// OriginValidator is a validator for the "origin" field enum values. It is called by the builders before save.
func OriginValidator(o Origin) error {
	switch o {
	case OriginOss, OriginCdn, OriginBoth:
		return nil
	default:
		return fmt.Errorf("domain: invalid enum value for origin field: %q", o)
	}
}

// ErrorKind defines the type for the "error_kind" enum field.
type ErrorKind string

// ErrorKindNone is the default value of the ErrorKind enum.
const DefaultErrorKind = ErrorKindNone

// ErrorKind values.
const (
	ErrorKindNone        ErrorKind = "none"
	ErrorKindTransient   ErrorKind = "transient"
	ErrorKindPermanent   ErrorKind = "permanent"
	ErrorKindRateLimited ErrorKind = "rate_limited"
)

func (ek ErrorKind) String() string {
	return string(ek)
}

// ErrorKindValidator is a validator for the "error_kind" field enum values. It is called by the builders before save.
func ErrorKindValidator(ek ErrorKind) error {
	switch ek {
	case ErrorKindNone, ErrorKindTransient, ErrorKindPermanent, ErrorKindRateLimited:
		return nil
	default:
		return fmt.Errorf("domain: invalid enum value for error_kind field: %q", ek)
	}
}

// OrderOption defines the ordering options for the Domain queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDomain orders the results by the domain field.
func ByDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomain, opts...).ToFunc()
}

// ByBucket orders the results by the bucket field.
func ByBucket(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBucket, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByAccountName orders the results by the account_name field.
func ByAccountName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountName, opts...).ToFunc()
}

// ByIssuedAt orders the results by the issued_at field.
func ByIssuedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCertPem orders the results by the cert_pem field.
func ByCertPem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCertPem, opts...).ToFunc()
}

// ByKeyPem orders the results by the key_pem field.
func ByKeyPem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyPem, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDeployTarget orders the results by the deploy_target field.
func ByDeployTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeployTarget, opts...).ToFunc()
}

// ByPresence orders the results by the presence field.
func ByPresence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPresence, opts...).ToFunc()
}

// ByOrigin orders the results by the origin field.
func ByOrigin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrigin, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByManaged orders the results by the managed field.
func ByManaged(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManaged, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByNextRetryAt orders the results by the next_retry_at field.
func ByNextRetryAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRetryAt, opts...).ToFunc()
}

// ByErrorKind orders the results by the error_kind field.
func ByErrorKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorKind, opts...).ToFunc()
}

// ByNotifiedState orders the results by the notified_state field.
func ByNotifiedState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifiedState, opts...).ToFunc()
}

// ByLastNotifiedAt orders the results by the last_notified_at field.
func ByLastNotifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastNotifiedAt, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByBlockedReason orders the results by the blocked_reason field.
func ByBlockedReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlockedReason, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
