// Code generated by ent, DO NOT EDIT.

package domain

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/solarhell/certship/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Domain {
	return predicate.Domain(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Domain {
	return predicate.Domain(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Domain {
	return predicate.Domain(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Domain {
	return predicate.Domain(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Domain {
	return predicate.Domain(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Domain {
	return predicate.Domain(sql.FieldContainsFold(FieldID, id))
}

// Domain applies equality check predicate on the "domain" field. It's identical to DomainEQ.
func Domain(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldDomain, v))
}

// Bucket applies equality check predicate on the "bucket" field. It's identical to BucketEQ.
func Bucket(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldBucket, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldRegion, v))
}

// AccountName applies equality check predicate on the "account_name" field. It's identical to AccountNameEQ.
func AccountName(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldAccountName, v))
}

// IssuedAt applies equality check predicate on the "issued_at" field. It's identical to IssuedAtEQ.
func IssuedAt(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldIssuedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldExpiresAt, v))
}

// CertPem applies equality check predicate on the "cert_pem" field. It's identical to CertPemEQ.
func CertPem(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldCertPem, v))
}

// KeyPem applies equality check predicate on the "key_pem" field. It's identical to KeyPemEQ.
func KeyPem(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldKeyPem, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldErrorMessage, v))
}

// BlockedReason applies equality check predicate on the "blocked_reason" field. It's identical to BlockedReasonEQ.
func BlockedReason(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldBlockedReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldUpdatedAt, v))
}

// DomainEQ applies the EQ predicate on the "domain" field.
func DomainEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldDomain, v))
}

// DomainNEQ applies the NEQ predicate on the "domain" field.
func DomainNEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldDomain, v))
}

// DomainIn applies the In predicate on the "domain" field.
func DomainIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldDomain, vs...))
}

// DomainNotIn applies the NotIn predicate on the "domain" field.
func DomainNotIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldDomain, vs...))
}

// DomainGT applies the GT predicate on the "domain" field.
func DomainGT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGT(FieldDomain, v))
}

// DomainGTE applies the GTE predicate on the "domain" field.
func DomainGTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGTE(FieldDomain, v))
}

// DomainLT applies the LT predicate on the "domain" field.
func DomainLT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLT(FieldDomain, v))
}

// DomainLTE applies the LTE predicate on the "domain" field.
func DomainLTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLTE(FieldDomain, v))
}

// DomainContains applies the Contains predicate on the "domain" field.
func DomainContains(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContains(FieldDomain, v))
}

// DomainHasPrefix applies the HasPrefix predicate on the "domain" field.
func DomainHasPrefix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasPrefix(FieldDomain, v))
}

// DomainHasSuffix applies the HasSuffix predicate on the "domain" field.
func DomainHasSuffix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasSuffix(FieldDomain, v))
}

// DomainEqualFold applies the EqualFold predicate on the "domain" field.
func DomainEqualFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEqualFold(FieldDomain, v))
}

// DomainContainsFold applies the ContainsFold predicate on the "domain" field.
func DomainContainsFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContainsFold(FieldDomain, v))
}

// BucketEQ applies the EQ predicate on the "bucket" field.
func BucketEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldBucket, v))
}

// BucketNEQ applies the NEQ predicate on the "bucket" field.
func BucketNEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldBucket, v))
}

// BucketIn applies the In predicate on the "bucket" field.
func BucketIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldBucket, vs...))
}

// BucketNotIn applies the NotIn predicate on the "bucket" field.
func BucketNotIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldBucket, vs...))
}

// BucketGT applies the GT predicate on the "bucket" field.
func BucketGT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGT(FieldBucket, v))
}

// BucketGTE applies the GTE predicate on the "bucket" field.
func BucketGTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGTE(FieldBucket, v))
}

// BucketLT applies the LT predicate on the "bucket" field.
func BucketLT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLT(FieldBucket, v))
}

// BucketLTE applies the LTE predicate on the "bucket" field.
func BucketLTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLTE(FieldBucket, v))
}

// BucketContains applies the Contains predicate on the "bucket" field.
func BucketContains(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContains(FieldBucket, v))
}

// BucketHasPrefix applies the HasPrefix predicate on the "bucket" field.
func BucketHasPrefix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasPrefix(FieldBucket, v))
}

// BucketHasSuffix applies the HasSuffix predicate on the "bucket" field.
func BucketHasSuffix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasSuffix(FieldBucket, v))
}

// BucketEqualFold applies the EqualFold predicate on the "bucket" field.
func BucketEqualFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEqualFold(FieldBucket, v))
}

// BucketContainsFold applies the ContainsFold predicate on the "bucket" field.
func BucketContainsFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContainsFold(FieldBucket, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContainsFold(FieldRegion, v))
}

// AccountNameEQ applies the EQ predicate on the "account_name" field.
func AccountNameEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldAccountName, v))
}

// AccountNameNEQ applies the NEQ predicate on the "account_name" field.
func AccountNameNEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldAccountName, v))
}

// AccountNameIn applies the In predicate on the "account_name" field.
func AccountNameIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldAccountName, vs...))
}

// AccountNameNotIn applies the NotIn predicate on the "account_name" field.
func AccountNameNotIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldAccountName, vs...))
}

// AccountNameGT applies the GT predicate on the "account_name" field.
func AccountNameGT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGT(FieldAccountName, v))
}

// AccountNameGTE applies the GTE predicate on the "account_name" field.
func AccountNameGTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGTE(FieldAccountName, v))
}

// AccountNameLT applies the LT predicate on the "account_name" field.
func AccountNameLT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLT(FieldAccountName, v))
}

// AccountNameLTE applies the LTE predicate on the "account_name" field.
func AccountNameLTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLTE(FieldAccountName, v))
}

// AccountNameContains applies the Contains predicate on the "account_name" field.
func AccountNameContains(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContains(FieldAccountName, v))
}

// AccountNameHasPrefix applies the HasPrefix predicate on the "account_name" field.
func AccountNameHasPrefix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasPrefix(FieldAccountName, v))
}

// AccountNameHasSuffix applies the HasSuffix predicate on the "account_name" field.
func AccountNameHasSuffix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasSuffix(FieldAccountName, v))
}

// AccountNameEqualFold applies the EqualFold predicate on the "account_name" field.
func AccountNameEqualFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEqualFold(FieldAccountName, v))
}

// AccountNameContainsFold applies the ContainsFold predicate on the "account_name" field.
func AccountNameContainsFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContainsFold(FieldAccountName, v))
}

// IssuedAtEQ applies the EQ predicate on the "issued_at" field.
func IssuedAtEQ(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedAtNEQ applies the NEQ predicate on the "issued_at" field.
func IssuedAtNEQ(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldIssuedAt, v))
}

// IssuedAtIn applies the In predicate on the "issued_at" field.
func IssuedAtIn(vs ...time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldIssuedAt, vs...))
}

// IssuedAtNotIn applies the NotIn predicate on the "issued_at" field.
func IssuedAtNotIn(vs ...time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldIssuedAt, vs...))
}

// IssuedAtGT applies the GT predicate on the "issued_at" field.
func IssuedAtGT(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldGT(FieldIssuedAt, v))
}

// IssuedAtGTE applies the GTE predicate on the "issued_at" field.
func IssuedAtGTE(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldGTE(FieldIssuedAt, v))
}

// IssuedAtLT applies the LT predicate on the "issued_at" field.
func IssuedAtLT(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldLT(FieldIssuedAt, v))
}

// IssuedAtLTE applies the LTE predicate on the "issued_at" field.
func IssuedAtLTE(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldLTE(FieldIssuedAt, v))
}

// IssuedAtIsNil applies the IsNil predicate on the "issued_at" field.
func IssuedAtIsNil() predicate.Domain {
	return predicate.Domain(sql.FieldIsNull(FieldIssuedAt))
}

// IssuedAtNotNil applies the NotNil predicate on the "issued_at" field.
func IssuedAtNotNil() predicate.Domain {
	return predicate.Domain(sql.FieldNotNull(FieldIssuedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.Domain {
	return predicate.Domain(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.Domain {
	return predicate.Domain(sql.FieldNotNull(FieldExpiresAt))
}

// CertPemEQ applies the EQ predicate on the "cert_pem" field.
func CertPemEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldCertPem, v))
}

// CertPemNEQ applies the NEQ predicate on the "cert_pem" field.
func CertPemNEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldCertPem, v))
}

// CertPemIn applies the In predicate on the "cert_pem" field.
func CertPemIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldCertPem, vs...))
}

// CertPemNotIn applies the NotIn predicate on the "cert_pem" field.
func CertPemNotIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldCertPem, vs...))
}

// CertPemGT applies the GT predicate on the "cert_pem" field.
func CertPemGT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGT(FieldCertPem, v))
}

// CertPemGTE applies the GTE predicate on the "cert_pem" field.
func CertPemGTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGTE(FieldCertPem, v))
}

// CertPemLT applies the LT predicate on the "cert_pem" field.
func CertPemLT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLT(FieldCertPem, v))
}

// CertPemLTE applies the LTE predicate on the "cert_pem" field.
func CertPemLTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLTE(FieldCertPem, v))
}

// CertPemContains applies the Contains predicate on the "cert_pem" field.
func CertPemContains(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContains(FieldCertPem, v))
}

// CertPemHasPrefix applies the HasPrefix predicate on the "cert_pem" field.
func CertPemHasPrefix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasPrefix(FieldCertPem, v))
}

// CertPemHasSuffix applies the HasSuffix predicate on the "cert_pem" field.
func CertPemHasSuffix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasSuffix(FieldCertPem, v))
}

// CertPemIsNil applies the IsNil predicate on the "cert_pem" field.
func CertPemIsNil() predicate.Domain {
	return predicate.Domain(sql.FieldIsNull(FieldCertPem))
}

// CertPemNotNil applies the NotNil predicate on the "cert_pem" field.
func CertPemNotNil() predicate.Domain {
	return predicate.Domain(sql.FieldNotNull(FieldCertPem))
}

// CertPemEqualFold applies the EqualFold predicate on the "cert_pem" field.
func CertPemEqualFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEqualFold(FieldCertPem, v))
}

// CertPemContainsFold applies the ContainsFold predicate on the "cert_pem" field.
func CertPemContainsFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContainsFold(FieldCertPem, v))
}

// KeyPemEQ applies the EQ predicate on the "key_pem" field.
func KeyPemEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldKeyPem, v))
}

// KeyPemNEQ applies the NEQ predicate on the "key_pem" field.
func KeyPemNEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldKeyPem, v))
}

// KeyPemIn applies the In predicate on the "key_pem" field.
func KeyPemIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldKeyPem, vs...))
}

// KeyPemNotIn applies the NotIn predicate on the "key_pem" field.
func KeyPemNotIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldKeyPem, vs...))
}

// KeyPemGT applies the GT predicate on the "key_pem" field.
func KeyPemGT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGT(FieldKeyPem, v))
}

// KeyPemGTE applies the GTE predicate on the "key_pem" field.
func KeyPemGTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGTE(FieldKeyPem, v))
}

// KeyPemLT applies the LT predicate on the "key_pem" field.
func KeyPemLT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLT(FieldKeyPem, v))
}

// KeyPemLTE applies the LTE predicate on the "key_pem" field.
func KeyPemLTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLTE(FieldKeyPem, v))
}

// KeyPemContains applies the Contains predicate on the "key_pem" field.
func KeyPemContains(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContains(FieldKeyPem, v))
}

// KeyPemHasPrefix applies the HasPrefix predicate on the "key_pem" field.
func KeyPemHasPrefix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasPrefix(FieldKeyPem, v))
}

// KeyPemHasSuffix applies the HasSuffix predicate on the "key_pem" field.
func KeyPemHasSuffix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasSuffix(FieldKeyPem, v))
}

// KeyPemIsNil applies the IsNil predicate on the "key_pem" field.
func KeyPemIsNil() predicate.Domain {
	return predicate.Domain(sql.FieldIsNull(FieldKeyPem))
}

// KeyPemNotNil applies the NotNil predicate on the "key_pem" field.
func KeyPemNotNil() predicate.Domain {
	return predicate.Domain(sql.FieldNotNull(FieldKeyPem))
}

// KeyPemEqualFold applies the EqualFold predicate on the "key_pem" field.
func KeyPemEqualFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEqualFold(FieldKeyPem, v))
}

// KeyPemContainsFold applies the ContainsFold predicate on the "key_pem" field.
func KeyPemContainsFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContainsFold(FieldKeyPem, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldStatus, vs...))
}

// DeployTargetEQ applies the EQ predicate on the "deploy_target" field.
func DeployTargetEQ(v DeployTarget) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldDeployTarget, v))
}

// DeployTargetNEQ applies the NEQ predicate on the "deploy_target" field.
func DeployTargetNEQ(v DeployTarget) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldDeployTarget, v))
}

// DeployTargetIn applies the In predicate on the "deploy_target" field.
func DeployTargetIn(vs ...DeployTarget) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldDeployTarget, vs...))
}

// DeployTargetNotIn applies the NotIn predicate on the "deploy_target" field.
func DeployTargetNotIn(vs ...DeployTarget) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldDeployTarget, vs...))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.Domain {
	return predicate.Domain(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.Domain {
	return predicate.Domain(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContainsFold(FieldErrorMessage, v))
}

// BlockedReasonEQ applies the EQ predicate on the "blocked_reason" field.
func BlockedReasonEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldBlockedReason, v))
}

// BlockedReasonNEQ applies the NEQ predicate on the "blocked_reason" field.
func BlockedReasonNEQ(v string) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldBlockedReason, v))
}

// BlockedReasonIn applies the In predicate on the "blocked_reason" field.
func BlockedReasonIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldBlockedReason, vs...))
}

// BlockedReasonNotIn applies the NotIn predicate on the "blocked_reason" field.
func BlockedReasonNotIn(vs ...string) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldBlockedReason, vs...))
}

// BlockedReasonGT applies the GT predicate on the "blocked_reason" field.
func BlockedReasonGT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGT(FieldBlockedReason, v))
}

// BlockedReasonGTE applies the GTE predicate on the "blocked_reason" field.
func BlockedReasonGTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldGTE(FieldBlockedReason, v))
}

// BlockedReasonLT applies the LT predicate on the "blocked_reason" field.
func BlockedReasonLT(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLT(FieldBlockedReason, v))
}

// BlockedReasonLTE applies the LTE predicate on the "blocked_reason" field.
func BlockedReasonLTE(v string) predicate.Domain {
	return predicate.Domain(sql.FieldLTE(FieldBlockedReason, v))
}

// BlockedReasonContains applies the Contains predicate on the "blocked_reason" field.
func BlockedReasonContains(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContains(FieldBlockedReason, v))
}

// BlockedReasonHasPrefix applies the HasPrefix predicate on the "blocked_reason" field.
func BlockedReasonHasPrefix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasPrefix(FieldBlockedReason, v))
}

// BlockedReasonHasSuffix applies the HasSuffix predicate on the "blocked_reason" field.
func BlockedReasonHasSuffix(v string) predicate.Domain {
	return predicate.Domain(sql.FieldHasSuffix(FieldBlockedReason, v))
}

// BlockedReasonIsNil applies the IsNil predicate on the "blocked_reason" field.
func BlockedReasonIsNil() predicate.Domain {
	return predicate.Domain(sql.FieldIsNull(FieldBlockedReason))
}

// BlockedReasonNotNil applies the NotNil predicate on the "blocked_reason" field.
func BlockedReasonNotNil() predicate.Domain {
	return predicate.Domain(sql.FieldNotNull(FieldBlockedReason))
}

// BlockedReasonEqualFold applies the EqualFold predicate on the "blocked_reason" field.
func BlockedReasonEqualFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldEqualFold(FieldBlockedReason, v))
}

// BlockedReasonContainsFold applies the ContainsFold predicate on the "blocked_reason" field.
func BlockedReasonContainsFold(v string) predicate.Domain {
	return predicate.Domain(sql.FieldContainsFold(FieldBlockedReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Domain {
	return predicate.Domain(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Domain) predicate.Domain {
	return predicate.Domain(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Domain) predicate.Domain {
	return predicate.Domain(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Domain) predicate.Domain {
	return predicate.Domain(sql.NotPredicates(p))
}
