// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solarhell/certship/pkg/ent/certificate"
	"github.com/solarhell/certship/pkg/ent/predicate"
)

// CertificateUpdate is the builder for updating Certificate entities.
type CertificateUpdate struct {
	config
	hooks    []Hook
	mutation *CertificateMutation
}

// Where appends a list predicates to the CertificateUpdate builder.
func (_u *CertificateUpdate) Where(ps ...predicate.Certificate) *CertificateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDomain sets the "domain" field.
func (_u *CertificateUpdate) SetDomain(v string) *CertificateUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableDomain(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *CertificateUpdate) SetBucket(v string) *CertificateUpdate {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableBucket(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *CertificateUpdate) SetRegion(v string) *CertificateUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableRegion(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetAccountName sets the "account_name" field.
func (_u *CertificateUpdate) SetAccountName(v string) *CertificateUpdate {
	_u.mutation.SetAccountName(v)
	return _u
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableAccountName(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetAccountName(*v)
	}
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *CertificateUpdate) SetIssuedAt(v time.Time) *CertificateUpdate {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableIssuedAt(v *time.Time) *CertificateUpdate {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *CertificateUpdate) ClearIssuedAt() *CertificateUpdate {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CertificateUpdate) SetExpiresAt(v time.Time) *CertificateUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableExpiresAt(v *time.Time) *CertificateUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *CertificateUpdate) ClearExpiresAt() *CertificateUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetCertPem sets the "cert_pem" field.
func (_u *CertificateUpdate) SetCertPem(v string) *CertificateUpdate {
	_u.mutation.SetCertPem(v)
	return _u
}

// SetNillableCertPem sets the "cert_pem" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableCertPem(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetCertPem(*v)
	}
	return _u
}

// ClearCertPem clears the value of the "cert_pem" field.
func (_u *CertificateUpdate) ClearCertPem() *CertificateUpdate {
	_u.mutation.ClearCertPem()
	return _u
}

// SetKeyPem sets the "key_pem" field.
func (_u *CertificateUpdate) SetKeyPem(v string) *CertificateUpdate {
	_u.mutation.SetKeyPem(v)
	return _u
}

// SetNillableKeyPem sets the "key_pem" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableKeyPem(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetKeyPem(*v)
	}
	return _u
}

// ClearKeyPem clears the value of the "key_pem" field.
func (_u *CertificateUpdate) ClearKeyPem() *CertificateUpdate {
	_u.mutation.ClearKeyPem()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CertificateUpdate) SetStatus(v certificate.Status) *CertificateUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableStatus(v *certificate.Status) *CertificateUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *CertificateUpdate) SetErrorMessage(v string) *CertificateUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableErrorMessage(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *CertificateUpdate) ClearErrorMessage() *CertificateUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CertificateUpdate) SetUpdatedAt(v time.Time) *CertificateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CertificateMutation object of the builder.
func (_u *CertificateUpdate) Mutation() *CertificateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CertificateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CertificateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CertificateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CertificateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CertificateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := certificate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CertificateUpdate) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := certificate.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Certificate.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bucket(); ok {
		if err := certificate.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "Certificate.bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := certificate.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "Certificate.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountName(); ok {
		if err := certificate.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "account_name", err: fmt.Errorf(`ent: validator failed for field "Certificate.account_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := certificate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Certificate.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CertificateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(certificate.Table, certificate.Columns, sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(certificate.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(certificate.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(certificate.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountName(); ok {
		_spec.SetField(certificate.FieldAccountName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(certificate.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(certificate.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(certificate.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(certificate.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CertPem(); ok {
		_spec.SetField(certificate.FieldCertPem, field.TypeString, value)
	}
	if _u.mutation.CertPemCleared() {
		_spec.ClearField(certificate.FieldCertPem, field.TypeString)
	}
	if value, ok := _u.mutation.KeyPem(); ok {
		_spec.SetField(certificate.FieldKeyPem, field.TypeString, value)
	}
	if _u.mutation.KeyPemCleared() {
		_spec.ClearField(certificate.FieldKeyPem, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(certificate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(certificate.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(certificate.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(certificate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CertificateUpdateOne is the builder for updating a single Certificate entity.
type CertificateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CertificateMutation
}

// SetDomain sets the "domain" field.
func (_u *CertificateUpdateOne) SetDomain(v string) *CertificateUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableDomain(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *CertificateUpdateOne) SetBucket(v string) *CertificateUpdateOne {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableBucket(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *CertificateUpdateOne) SetRegion(v string) *CertificateUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableRegion(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetAccountName sets the "account_name" field.
func (_u *CertificateUpdateOne) SetAccountName(v string) *CertificateUpdateOne {
	_u.mutation.SetAccountName(v)
	return _u
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableAccountName(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetAccountName(*v)
	}
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *CertificateUpdateOne) SetIssuedAt(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableIssuedAt(v *time.Time) *CertificateUpdateOne {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *CertificateUpdateOne) ClearIssuedAt() *CertificateUpdateOne {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CertificateUpdateOne) SetExpiresAt(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableExpiresAt(v *time.Time) *CertificateUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *CertificateUpdateOne) ClearExpiresAt() *CertificateUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetCertPem sets the "cert_pem" field.
func (_u *CertificateUpdateOne) SetCertPem(v string) *CertificateUpdateOne {
	_u.mutation.SetCertPem(v)
	return _u
}

// SetNillableCertPem sets the "cert_pem" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableCertPem(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetCertPem(*v)
	}
	return _u
}

// ClearCertPem clears the value of the "cert_pem" field.
func (_u *CertificateUpdateOne) ClearCertPem() *CertificateUpdateOne {
	_u.mutation.ClearCertPem()
	return _u
}

// SetKeyPem sets the "key_pem" field.
func (_u *CertificateUpdateOne) SetKeyPem(v string) *CertificateUpdateOne {
	_u.mutation.SetKeyPem(v)
	return _u
}

// SetNillableKeyPem sets the "key_pem" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableKeyPem(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetKeyPem(*v)
	}
	return _u
}

// ClearKeyPem clears the value of the "key_pem" field.
func (_u *CertificateUpdateOne) ClearKeyPem() *CertificateUpdateOne {
	_u.mutation.ClearKeyPem()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CertificateUpdateOne) SetStatus(v certificate.Status) *CertificateUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableStatus(v *certificate.Status) *CertificateUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *CertificateUpdateOne) SetErrorMessage(v string) *CertificateUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableErrorMessage(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *CertificateUpdateOne) ClearErrorMessage() *CertificateUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CertificateUpdateOne) SetUpdatedAt(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CertificateMutation object of the builder.
func (_u *CertificateUpdateOne) Mutation() *CertificateMutation {
	return _u.mutation
}

// Where appends a list predicates to the CertificateUpdate builder.
func (_u *CertificateUpdateOne) Where(ps ...predicate.Certificate) *CertificateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CertificateUpdateOne) Select(field string, fields ...string) *CertificateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Certificate entity.
func (_u *CertificateUpdateOne) Save(ctx context.Context) (*Certificate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CertificateUpdateOne) SaveX(ctx context.Context) *Certificate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CertificateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CertificateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CertificateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := certificate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CertificateUpdateOne) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := certificate.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Certificate.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bucket(); ok {
		if err := certificate.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "Certificate.bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := certificate.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "Certificate.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountName(); ok {
		if err := certificate.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "account_name", err: fmt.Errorf(`ent: validator failed for field "Certificate.account_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := certificate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Certificate.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CertificateUpdateOne) sqlSave(ctx context.Context) (_node *Certificate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(certificate.Table, certificate.Columns, sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Certificate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, certificate.FieldID)
		for _, f := range fields {
			if !certificate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != certificate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(certificate.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(certificate.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(certificate.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountName(); ok {
		_spec.SetField(certificate.FieldAccountName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(certificate.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(certificate.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(certificate.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(certificate.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CertPem(); ok {
		_spec.SetField(certificate.FieldCertPem, field.TypeString, value)
	}
	if _u.mutation.CertPemCleared() {
		_spec.ClearField(certificate.FieldCertPem, field.TypeString)
	}
	if value, ok := _u.mutation.KeyPem(); ok {
		_spec.SetField(certificate.FieldKeyPem, field.TypeString, value)
	}
	if _u.mutation.KeyPemCleared() {
		_spec.ClearField(certificate.FieldKeyPem, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(certificate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(certificate.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(certificate.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(certificate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Certificate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
