// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solarhell/certship/pkg/ent/cloudaccount"
	"github.com/solarhell/certship/pkg/ent/predicate"
)

// CloudAccountUpdate is the builder for updating CloudAccount entities.
type CloudAccountUpdate struct {
	config
	hooks    []Hook
	mutation *CloudAccountMutation
}

// Where appends a list predicates to the CloudAccountUpdate builder.
func (_u *CloudAccountUpdate) Where(ps ...predicate.CloudAccount) *CloudAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CloudAccountUpdate) SetName(v string) *CloudAccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CloudAccountUpdate) SetNillableName(v *string) *CloudAccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAccessKeyID sets the "access_key_id" field.
func (_u *CloudAccountUpdate) SetAccessKeyID(v string) *CloudAccountUpdate {
	_u.mutation.SetAccessKeyID(v)
	return _u
}

// SetNillableAccessKeyID sets the "access_key_id" field if the given value is not nil.
func (_u *CloudAccountUpdate) SetNillableAccessKeyID(v *string) *CloudAccountUpdate {
	if v != nil {
		_u.SetAccessKeyID(*v)
	}
	return _u
}

// SetAccessKeySecret sets the "access_key_secret" field.
func (_u *CloudAccountUpdate) SetAccessKeySecret(v string) *CloudAccountUpdate {
	_u.mutation.SetAccessKeySecret(v)
	return _u
}

// SetNillableAccessKeySecret sets the "access_key_secret" field if the given value is not nil.
func (_u *CloudAccountUpdate) SetNillableAccessKeySecret(v *string) *CloudAccountUpdate {
	if v != nil {
		_u.SetAccessKeySecret(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *CloudAccountUpdate) SetEnabled(v bool) *CloudAccountUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *CloudAccountUpdate) SetNillableEnabled(v *bool) *CloudAccountUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CloudAccountUpdate) SetUpdatedAt(v time.Time) *CloudAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CloudAccountMutation object of the builder.
func (_u *CloudAccountUpdate) Mutation() *CloudAccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CloudAccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CloudAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CloudAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CloudAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CloudAccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cloudaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CloudAccountUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := cloudaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessKeyID(); ok {
		if err := cloudaccount.AccessKeyIDValidator(v); err != nil {
			return &ValidationError{Name: "access_key_id", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.access_key_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessKeySecret(); ok {
		if err := cloudaccount.AccessKeySecretValidator(v); err != nil {
			return &ValidationError{Name: "access_key_secret", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.access_key_secret": %w`, err)}
		}
	}
	return nil
}

func (_u *CloudAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cloudaccount.Table, cloudaccount.Columns, sqlgraph.NewFieldSpec(cloudaccount.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(cloudaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessKeyID(); ok {
		_spec.SetField(cloudaccount.FieldAccessKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessKeySecret(); ok {
		_spec.SetField(cloudaccount.FieldAccessKeySecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(cloudaccount.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cloudaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cloudaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CloudAccountUpdateOne is the builder for updating a single CloudAccount entity.
type CloudAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CloudAccountMutation
}

// SetName sets the "name" field.
func (_u *CloudAccountUpdateOne) SetName(v string) *CloudAccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CloudAccountUpdateOne) SetNillableName(v *string) *CloudAccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAccessKeyID sets the "access_key_id" field.
func (_u *CloudAccountUpdateOne) SetAccessKeyID(v string) *CloudAccountUpdateOne {
	_u.mutation.SetAccessKeyID(v)
	return _u
}

// SetNillableAccessKeyID sets the "access_key_id" field if the given value is not nil.
func (_u *CloudAccountUpdateOne) SetNillableAccessKeyID(v *string) *CloudAccountUpdateOne {
	if v != nil {
		_u.SetAccessKeyID(*v)
	}
	return _u
}

// SetAccessKeySecret sets the "access_key_secret" field.
func (_u *CloudAccountUpdateOne) SetAccessKeySecret(v string) *CloudAccountUpdateOne {
	_u.mutation.SetAccessKeySecret(v)
	return _u
}

// SetNillableAccessKeySecret sets the "access_key_secret" field if the given value is not nil.
func (_u *CloudAccountUpdateOne) SetNillableAccessKeySecret(v *string) *CloudAccountUpdateOne {
	if v != nil {
		_u.SetAccessKeySecret(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *CloudAccountUpdateOne) SetEnabled(v bool) *CloudAccountUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *CloudAccountUpdateOne) SetNillableEnabled(v *bool) *CloudAccountUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CloudAccountUpdateOne) SetUpdatedAt(v time.Time) *CloudAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CloudAccountMutation object of the builder.
func (_u *CloudAccountUpdateOne) Mutation() *CloudAccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the CloudAccountUpdate builder.
func (_u *CloudAccountUpdateOne) Where(ps ...predicate.CloudAccount) *CloudAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CloudAccountUpdateOne) Select(field string, fields ...string) *CloudAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CloudAccount entity.
func (_u *CloudAccountUpdateOne) Save(ctx context.Context) (*CloudAccount, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CloudAccountUpdateOne) SaveX(ctx context.Context) *CloudAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CloudAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CloudAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CloudAccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cloudaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CloudAccountUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := cloudaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessKeyID(); ok {
		if err := cloudaccount.AccessKeyIDValidator(v); err != nil {
			return &ValidationError{Name: "access_key_id", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.access_key_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessKeySecret(); ok {
		if err := cloudaccount.AccessKeySecretValidator(v); err != nil {
			return &ValidationError{Name: "access_key_secret", err: fmt.Errorf(`ent: validator failed for field "CloudAccount.access_key_secret": %w`, err)}
		}
	}
	return nil
}

func (_u *CloudAccountUpdateOne) sqlSave(ctx context.Context) (_node *CloudAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cloudaccount.Table, cloudaccount.Columns, sqlgraph.NewFieldSpec(cloudaccount.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CloudAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cloudaccount.FieldID)
		for _, f := range fields {
			if !cloudaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cloudaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(cloudaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessKeyID(); ok {
		_spec.SetField(cloudaccount.FieldAccessKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessKeySecret(); ok {
		_spec.SetField(cloudaccount.FieldAccessKeySecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(cloudaccount.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cloudaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CloudAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cloudaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
