// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solarhell/certship/pkg/ent/domain"
	"github.com/solarhell/certship/pkg/ent/predicate"
)

// DomainUpdate is the builder for updating Domain entities.
type DomainUpdate struct {
	config
	hooks    []Hook
	mutation *DomainMutation
}

// Where appends a list predicates to the DomainUpdate builder.
func (_u *DomainUpdate) Where(ps ...predicate.Domain) *DomainUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDomain sets the "domain" field.
func (_u *DomainUpdate) SetDomain(v string) *DomainUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *DomainUpdate) SetNillableDomain(v *string) *DomainUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *DomainUpdate) SetBucket(v string) *DomainUpdate {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *DomainUpdate) SetNillableBucket(v *string) *DomainUpdate {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *DomainUpdate) SetRegion(v string) *DomainUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *DomainUpdate) SetNillableRegion(v *string) *DomainUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetAccountName sets the "account_name" field.
func (_u *DomainUpdate) SetAccountName(v string) *DomainUpdate {
	_u.mutation.SetAccountName(v)
	return _u
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (_u *DomainUpdate) SetNillableAccountName(v *string) *DomainUpdate {
	if v != nil {
		_u.SetAccountName(*v)
	}
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *DomainUpdate) SetIssuedAt(v time.Time) *DomainUpdate {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *DomainUpdate) SetNillableIssuedAt(v *time.Time) *DomainUpdate {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *DomainUpdate) ClearIssuedAt() *DomainUpdate {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DomainUpdate) SetExpiresAt(v time.Time) *DomainUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DomainUpdate) SetNillableExpiresAt(v *time.Time) *DomainUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *DomainUpdate) ClearExpiresAt() *DomainUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetCertPem sets the "cert_pem" field.
func (_u *DomainUpdate) SetCertPem(v string) *DomainUpdate {
	_u.mutation.SetCertPem(v)
	return _u
}

// SetNillableCertPem sets the "cert_pem" field if the given value is not nil.
func (_u *DomainUpdate) SetNillableCertPem(v *string) *DomainUpdate {
	if v != nil {
		_u.SetCertPem(*v)
	}
	return _u
}

// ClearCertPem clears the value of the "cert_pem" field.
func (_u *DomainUpdate) ClearCertPem() *DomainUpdate {
	_u.mutation.ClearCertPem()
	return _u
}

// SetKeyPem sets the "key_pem" field.
func (_u *DomainUpdate) SetKeyPem(v string) *DomainUpdate {
	_u.mutation.SetKeyPem(v)
	return _u
}

// SetNillableKeyPem sets the "key_pem" field if the given value is not nil.
func (_u *DomainUpdate) SetNillableKeyPem(v *string) *DomainUpdate {
	if v != nil {
		_u.SetKeyPem(*v)
	}
	return _u
}

// ClearKeyPem clears the value of the "key_pem" field.
func (_u *DomainUpdate) ClearKeyPem() *DomainUpdate {
	_u.mutation.ClearKeyPem()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DomainUpdate) SetStatus(v domain.Status) *DomainUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DomainUpdate) SetNillableStatus(v *domain.Status) *DomainUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *DomainUpdate) SetErrorMessage(v string) *DomainUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *DomainUpdate) SetNillableErrorMessage(v *string) *DomainUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *DomainUpdate) ClearErrorMessage() *DomainUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DomainUpdate) SetUpdatedAt(v time.Time) *DomainUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DomainMutation object of the builder.
func (_u *DomainUpdate) Mutation() *DomainMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DomainUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DomainUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DomainUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DomainUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DomainUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := domain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DomainUpdate) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := domain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Domain.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bucket(); ok {
		if err := domain.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "Domain.bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := domain.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "Domain.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountName(); ok {
		if err := domain.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "account_name", err: fmt.Errorf(`ent: validator failed for field "Domain.account_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := domain.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Domain.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DomainUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(domain.Table, domain.Columns, sqlgraph.NewFieldSpec(domain.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(domain.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(domain.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(domain.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountName(); ok {
		_spec.SetField(domain.FieldAccountName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(domain.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(domain.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(domain.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(domain.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CertPem(); ok {
		_spec.SetField(domain.FieldCertPem, field.TypeString, value)
	}
	if _u.mutation.CertPemCleared() {
		_spec.ClearField(domain.FieldCertPem, field.TypeString)
	}
	if value, ok := _u.mutation.KeyPem(); ok {
		_spec.SetField(domain.FieldKeyPem, field.TypeString, value)
	}
	if _u.mutation.KeyPemCleared() {
		_spec.ClearField(domain.FieldKeyPem, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(domain.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(domain.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(domain.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(domain.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{domain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DomainUpdateOne is the builder for updating a single Domain entity.
type DomainUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DomainMutation
}

// SetDomain sets the "domain" field.
func (_u *DomainUpdateOne) SetDomain(v string) *DomainUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *DomainUpdateOne) SetNillableDomain(v *string) *DomainUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *DomainUpdateOne) SetBucket(v string) *DomainUpdateOne {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *DomainUpdateOne) SetNillableBucket(v *string) *DomainUpdateOne {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *DomainUpdateOne) SetRegion(v string) *DomainUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *DomainUpdateOne) SetNillableRegion(v *string) *DomainUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetAccountName sets the "account_name" field.
func (_u *DomainUpdateOne) SetAccountName(v string) *DomainUpdateOne {
	_u.mutation.SetAccountName(v)
	return _u
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (_u *DomainUpdateOne) SetNillableAccountName(v *string) *DomainUpdateOne {
	if v != nil {
		_u.SetAccountName(*v)
	}
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *DomainUpdateOne) SetIssuedAt(v time.Time) *DomainUpdateOne {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *DomainUpdateOne) SetNillableIssuedAt(v *time.Time) *DomainUpdateOne {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *DomainUpdateOne) ClearIssuedAt() *DomainUpdateOne {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DomainUpdateOne) SetExpiresAt(v time.Time) *DomainUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DomainUpdateOne) SetNillableExpiresAt(v *time.Time) *DomainUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *DomainUpdateOne) ClearExpiresAt() *DomainUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetCertPem sets the "cert_pem" field.
func (_u *DomainUpdateOne) SetCertPem(v string) *DomainUpdateOne {
	_u.mutation.SetCertPem(v)
	return _u
}

// SetNillableCertPem sets the "cert_pem" field if the given value is not nil.
func (_u *DomainUpdateOne) SetNillableCertPem(v *string) *DomainUpdateOne {
	if v != nil {
		_u.SetCertPem(*v)
	}
	return _u
}

// ClearCertPem clears the value of the "cert_pem" field.
func (_u *DomainUpdateOne) ClearCertPem() *DomainUpdateOne {
	_u.mutation.ClearCertPem()
	return _u
}

// SetKeyPem sets the "key_pem" field.
func (_u *DomainUpdateOne) SetKeyPem(v string) *DomainUpdateOne {
	_u.mutation.SetKeyPem(v)
	return _u
}

// SetNillableKeyPem sets the "key_pem" field if the given value is not nil.
func (_u *DomainUpdateOne) SetNillableKeyPem(v *string) *DomainUpdateOne {
	if v != nil {
		_u.SetKeyPem(*v)
	}
	return _u
}

// ClearKeyPem clears the value of the "key_pem" field.
func (_u *DomainUpdateOne) ClearKeyPem() *DomainUpdateOne {
	_u.mutation.ClearKeyPem()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DomainUpdateOne) SetStatus(v domain.Status) *DomainUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DomainUpdateOne) SetNillableStatus(v *domain.Status) *DomainUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *DomainUpdateOne) SetErrorMessage(v string) *DomainUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *DomainUpdateOne) SetNillableErrorMessage(v *string) *DomainUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *DomainUpdateOne) ClearErrorMessage() *DomainUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DomainUpdateOne) SetUpdatedAt(v time.Time) *DomainUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DomainMutation object of the builder.
func (_u *DomainUpdateOne) Mutation() *DomainMutation {
	return _u.mutation
}

// Where appends a list predicates to the DomainUpdate builder.
func (_u *DomainUpdateOne) Where(ps ...predicate.Domain) *DomainUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DomainUpdateOne) Select(field string, fields ...string) *DomainUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Domain entity.
func (_u *DomainUpdateOne) Save(ctx context.Context) (*Domain, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DomainUpdateOne) SaveX(ctx context.Context) *Domain {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DomainUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DomainUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DomainUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := domain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DomainUpdateOne) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := domain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Domain.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bucket(); ok {
		if err := domain.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "Domain.bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := domain.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "Domain.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountName(); ok {
		if err := domain.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "account_name", err: fmt.Errorf(`ent: validator failed for field "Domain.account_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := domain.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Domain.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DomainUpdateOne) sqlSave(ctx context.Context) (_node *Domain, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(domain.Table, domain.Columns, sqlgraph.NewFieldSpec(domain.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Domain.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, domain.FieldID)
		for _, f := range fields {
			if !domain.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != domain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(domain.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(domain.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(domain.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountName(); ok {
		_spec.SetField(domain.FieldAccountName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(domain.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(domain.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(domain.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(domain.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CertPem(); ok {
		_spec.SetField(domain.FieldCertPem, field.TypeString, value)
	}
	if _u.mutation.CertPemCleared() {
		_spec.ClearField(domain.FieldCertPem, field.TypeString)
	}
	if value, ok := _u.mutation.KeyPem(); ok {
		_spec.SetField(domain.FieldKeyPem, field.TypeString, value)
	}
	if _u.mutation.KeyPemCleared() {
		_spec.ClearField(domain.FieldKeyPem, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(domain.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(domain.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(domain.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(domain.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Domain{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{domain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
