// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: certship/v1/renew_task.proto

package certshipv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/solarhell/certship/pkg/api/certship/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RenewTaskServiceName is the fully-qualified name of the RenewTaskService service.
	RenewTaskServiceName = "certship.v1.RenewTaskService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RenewTaskServiceListRenewTasksProcedure is the fully-qualified name of the RenewTaskService's
	// ListRenewTasks RPC.
	RenewTaskServiceListRenewTasksProcedure = "/certship.v1.RenewTaskService/ListRenewTasks"
	// RenewTaskServiceCreateRenewTaskProcedure is the fully-qualified name of the RenewTaskService's
	// CreateRenewTask RPC.
	RenewTaskServiceCreateRenewTaskProcedure = "/certship.v1.RenewTaskService/CreateRenewTask"
)

// RenewTaskServiceClient is a client for the certship.v1.RenewTaskService service.
type RenewTaskServiceClient interface {
	ListRenewTasks(context.Context, *connect.Request[v1.ListRenewTasksRequest]) (*connect.Response[v1.ListRenewTasksResponse], error)
	CreateRenewTask(context.Context, *connect.Request[v1.CreateRenewTaskRequest]) (*connect.Response[v1.CreateRenewTaskResponse], error)
}

// NewRenewTaskServiceClient constructs a client for the certship.v1.RenewTaskService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRenewTaskServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RenewTaskServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	renewTaskServiceMethods := v1.File_certship_v1_renew_task_proto.Services().ByName("RenewTaskService").Methods()
	return &renewTaskServiceClient{
		listRenewTasks: connect.NewClient[v1.ListRenewTasksRequest, v1.ListRenewTasksResponse](
			httpClient,
			baseURL+RenewTaskServiceListRenewTasksProcedure,
			connect.WithSchema(renewTaskServiceMethods.ByName("ListRenewTasks")),
			connect.WithClientOptions(opts...),
		),
		createRenewTask: connect.NewClient[v1.CreateRenewTaskRequest, v1.CreateRenewTaskResponse](
			httpClient,
			baseURL+RenewTaskServiceCreateRenewTaskProcedure,
			connect.WithSchema(renewTaskServiceMethods.ByName("CreateRenewTask")),
			connect.WithClientOptions(opts...),
		),
	}
}

// renewTaskServiceClient implements RenewTaskServiceClient.
type renewTaskServiceClient struct {
	listRenewTasks  *connect.Client[v1.ListRenewTasksRequest, v1.ListRenewTasksResponse]
	createRenewTask *connect.Client[v1.CreateRenewTaskRequest, v1.CreateRenewTaskResponse]
}

// ListRenewTasks calls certship.v1.RenewTaskService.ListRenewTasks.
func (c *renewTaskServiceClient) ListRenewTasks(ctx context.Context, req *connect.Request[v1.ListRenewTasksRequest]) (*connect.Response[v1.ListRenewTasksResponse], error) {
	return c.listRenewTasks.CallUnary(ctx, req)
}

// CreateRenewTask calls certship.v1.RenewTaskService.CreateRenewTask.
func (c *renewTaskServiceClient) CreateRenewTask(ctx context.Context, req *connect.Request[v1.CreateRenewTaskRequest]) (*connect.Response[v1.CreateRenewTaskResponse], error) {
	return c.createRenewTask.CallUnary(ctx, req)
}

// RenewTaskServiceHandler is an implementation of the certship.v1.RenewTaskService service.
type RenewTaskServiceHandler interface {
	ListRenewTasks(context.Context, *connect.Request[v1.ListRenewTasksRequest]) (*connect.Response[v1.ListRenewTasksResponse], error)
	CreateRenewTask(context.Context, *connect.Request[v1.CreateRenewTaskRequest]) (*connect.Response[v1.CreateRenewTaskResponse], error)
}

// NewRenewTaskServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRenewTaskServiceHandler(svc RenewTaskServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	renewTaskServiceMethods := v1.File_certship_v1_renew_task_proto.Services().ByName("RenewTaskService").Methods()
	renewTaskServiceListRenewTasksHandler := connect.NewUnaryHandler(
		RenewTaskServiceListRenewTasksProcedure,
		svc.ListRenewTasks,
		connect.WithSchema(renewTaskServiceMethods.ByName("ListRenewTasks")),
		connect.WithHandlerOptions(opts...),
	)
	renewTaskServiceCreateRenewTaskHandler := connect.NewUnaryHandler(
		RenewTaskServiceCreateRenewTaskProcedure,
		svc.CreateRenewTask,
		connect.WithSchema(renewTaskServiceMethods.ByName("CreateRenewTask")),
		connect.WithHandlerOptions(opts...),
	)
	return "/certship.v1.RenewTaskService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RenewTaskServiceListRenewTasksProcedure:
			renewTaskServiceListRenewTasksHandler.ServeHTTP(w, r)
		case RenewTaskServiceCreateRenewTaskProcedure:
			renewTaskServiceCreateRenewTaskHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRenewTaskServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRenewTaskServiceHandler struct{}

func (UnimplementedRenewTaskServiceHandler) ListRenewTasks(context.Context, *connect.Request[v1.ListRenewTasksRequest]) (*connect.Response[v1.ListRenewTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("certship.v1.RenewTaskService.ListRenewTasks is not implemented"))
}

func (UnimplementedRenewTaskServiceHandler) CreateRenewTask(context.Context, *connect.Request[v1.CreateRenewTaskRequest]) (*connect.Response[v1.CreateRenewTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("certship.v1.RenewTaskService.CreateRenewTask is not implemented"))
}
