// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: certship/v1/certificate.proto

package certshipv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCertificatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint64                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        *string                `protobuf:"bytes,2,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificatesRequest) Reset() {
	*x = ListCertificatesRequest{}
	mi := &file_certship_v1_certificate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificatesRequest) ProtoMessage() {}

func (x *ListCertificatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_certificate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificatesRequest.ProtoReflect.Descriptor instead.
func (*ListCertificatesRequest) Descriptor() ([]byte, []int) {
	return file_certship_v1_certificate_proto_rawDescGZIP(), []int{0}
}

func (x *ListCertificatesRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCertificatesRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type CertificateItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Bucket        string                 `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	AccountName   string                 `protobuf:"bytes,5,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	IssuedAt      string                 `protobuf:"bytes,7,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	DeployTarget  string                 `protobuf:"bytes,10,opt,name=deploy_target,json=deployTarget,proto3" json:"deploy_target,omitempty"`
	BlockedReason string                 `protobuf:"bytes,11,opt,name=blocked_reason,json=blockedReason,proto3" json:"blocked_reason,omitempty"`
	// present / missing / archived,域名在云上的存在性,与证书状态正交
	Presence string `protobuf:"bytes,12,opt,name=presence,proto3" json:"presence,omitempty"`
	// oss / cdn / both,域名的发现来源
	Origin string `protobuf:"bytes,13,opt,name=origin,proto3" json:"origin,omitempty"`
	// 最后一次在云上扫描到的时间,RFC3339
	LastSeenAt string `protobuf:"bytes,14,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	// 是否仍由 certship 托管签发续期
	Managed bool `protobuf:"varint,15,opt,name=managed,proto3" json:"managed,omitempty"`
	// 连续失败次数与下次重试时间
	RetryCount  uint32 `protobuf:"varint,16,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	NextRetryAt string `protobuf:"bytes,17,opt,name=next_retry_at,json=nextRetryAt,proto3" json:"next_retry_at,omitempty"`
	// none / transient / permanent / rate_limited
	ErrorKind     string `protobuf:"bytes,18,opt,name=error_kind,json=errorKind,proto3" json:"error_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateItem) Reset() {
	*x = CertificateItem{}
	mi := &file_certship_v1_certificate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateItem) ProtoMessage() {}

func (x *CertificateItem) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_certificate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateItem.ProtoReflect.Descriptor instead.
func (*CertificateItem) Descriptor() ([]byte, []int) {
	return file_certship_v1_certificate_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CertificateItem) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CertificateItem) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *CertificateItem) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CertificateItem) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *CertificateItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CertificateItem) GetIssuedAt() string {
	if x != nil {
		return x.IssuedAt
	}
	return ""
}

func (x *CertificateItem) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *CertificateItem) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CertificateItem) GetDeployTarget() string {
	if x != nil {
		return x.DeployTarget
	}
	return ""
}

func (x *CertificateItem) GetBlockedReason() string {
	if x != nil {
		return x.BlockedReason
	}
	return ""
}

func (x *CertificateItem) GetPresence() string {
	if x != nil {
		return x.Presence
	}
	return ""
}

func (x *CertificateItem) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CertificateItem) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *CertificateItem) GetManaged() bool {
	if x != nil {
		return x.Managed
	}
	return false
}

func (x *CertificateItem) GetRetryCount() uint32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *CertificateItem) GetNextRetryAt() string {
	if x != nil {
		return x.NextRetryAt
	}
	return ""
}

func (x *CertificateItem) GetErrorKind() string {
	if x != nil {
		return x.ErrorKind
	}
	return ""
}

type SetCertificateManagedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Managed       bool                   `protobuf:"varint,2,opt,name=managed,proto3" json:"managed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCertificateManagedRequest) Reset() {
	*x = SetCertificateManagedRequest{}
	mi := &file_certship_v1_certificate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCertificateManagedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCertificateManagedRequest) ProtoMessage() {}

func (x *SetCertificateManagedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_certificate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCertificateManagedRequest.ProtoReflect.Descriptor instead.
func (*SetCertificateManagedRequest) Descriptor() ([]byte, []int) {
	return file_certship_v1_certificate_proto_rawDescGZIP(), []int{2}
}

func (x *SetCertificateManagedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetCertificateManagedRequest) GetManaged() bool {
	if x != nil {
		return x.Managed
	}
	return false
}

type SetCertificateManagedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCertificateManagedResponse) Reset() {
	*x = SetCertificateManagedResponse{}
	mi := &file_certship_v1_certificate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCertificateManagedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCertificateManagedResponse) ProtoMessage() {}

func (x *SetCertificateManagedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_certificate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCertificateManagedResponse.ProtoReflect.Descriptor instead.
func (*SetCertificateManagedResponse) Descriptor() ([]byte, []int) {
	return file_certship_v1_certificate_proto_rawDescGZIP(), []int{3}
}

type DeleteCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCertificateRequest) Reset() {
	*x = DeleteCertificateRequest{}
	mi := &file_certship_v1_certificate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCertificateRequest) ProtoMessage() {}

func (x *DeleteCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_certificate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCertificateRequest.ProtoReflect.Descriptor instead.
func (*DeleteCertificateRequest) Descriptor() ([]byte, []int) {
	return file_certship_v1_certificate_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCertificateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCertificateResponse) Reset() {
	*x = DeleteCertificateResponse{}
	mi := &file_certship_v1_certificate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCertificateResponse) ProtoMessage() {}

func (x *DeleteCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_certificate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCertificateResponse.ProtoReflect.Descriptor instead.
func (*DeleteCertificateResponse) Descriptor() ([]byte, []int) {
	return file_certship_v1_certificate_proto_rawDescGZIP(), []int{5}
}

type ListCertificatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificates  []*CertificateItem     `protobuf:"bytes,1,rep,name=certificates,proto3" json:"certificates,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificatesResponse) Reset() {
	*x = ListCertificatesResponse{}
	mi := &file_certship_v1_certificate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificatesResponse) ProtoMessage() {}

func (x *ListCertificatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_certificate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificatesResponse.ProtoReflect.Descriptor instead.
func (*ListCertificatesResponse) Descriptor() ([]byte, []int) {
	return file_certship_v1_certificate_proto_rawDescGZIP(), []int{6}
}

func (x *ListCertificatesResponse) GetCertificates() []*CertificateItem {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *ListCertificatesResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

func (x *ListCertificatesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListCertificatesResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_certship_v1_certificate_proto protoreflect.FileDescriptor

const file_certship_v1_certificate_proto_rawDesc = "" +
	"\n" +
	"\x1dcertship/v1/certificate.proto\x12\vcertship.v1\"W\n" +
	"\x17ListCertificatesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x04R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x02 \x01(\tH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"\xa5\x04\n" +
	"\x0fCertificateItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12!\n" +
	"\faccount_name\x18\x05 \x01(\tR\vaccountName\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1b\n" +
	"\tissued_at\x18\a \x01(\tR\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\tR\texpiresAt\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12#\n" +
	"\rdeploy_target\x18\n" +
	" \x01(\tR\fdeployTarget\x12%\n" +
	"\x0eblocked_reason\x18\v \x01(\tR\rblockedReason\x12\x1a\n" +
	"\bpresence\x18\f \x01(\tR\bpresence\x12\x16\n" +
	"\x06origin\x18\r \x01(\tR\x06origin\x12 \n" +
	"\flast_seen_at\x18\x0e \x01(\tR\n" +
	"lastSeenAt\x12\x18\n" +
	"\amanaged\x18\x0f \x01(\bR\amanaged\x12\x1f\n" +
	"\vretry_count\x18\x10 \x01(\rR\n" +
	"retryCount\x12\"\n" +
	"\rnext_retry_at\x18\x11 \x01(\tR\vnextRetryAt\x12\x1d\n" +
	"\n" +
	"error_kind\x18\x12 \x01(\tR\terrorKind\"H\n" +
	"\x1cSetCertificateManagedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amanaged\x18\x02 \x01(\bR\amanaged\"\x1f\n" +
	"\x1dSetCertificateManagedResponse\"*\n" +
	"\x18DeleteCertificateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19DeleteCertificateResponse\"\xce\x01\n" +
	"\x18ListCertificatesResponse\x12@\n" +
	"\fcertificates\x18\x01 \x03(\v2\x1c.certship.v1.CertificateItemR\fcertificates\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x04R\n" +
	"totalCountB\x0e\n" +
	"\f_next_cursor2\xc9\x02\n" +
	"\x12CertificateService\x12_\n" +
	"\x10ListCertificates\x12$.certship.v1.ListCertificatesRequest\x1a%.certship.v1.ListCertificatesResponse\x12n\n" +
	"\x15SetCertificateManaged\x12).certship.v1.SetCertificateManagedRequest\x1a*.certship.v1.SetCertificateManagedResponse\x12b\n" +
	"\x11DeleteCertificate\x12%.certship.v1.DeleteCertificateRequest\x1a&.certship.v1.DeleteCertificateResponseB>Z<github.com/solarhell/certship/pkg/api/certship/v1;certshipv1b\x06proto3"

var (
	file_certship_v1_certificate_proto_rawDescOnce sync.Once
	file_certship_v1_certificate_proto_rawDescData []byte
)

func file_certship_v1_certificate_proto_rawDescGZIP() []byte {
	file_certship_v1_certificate_proto_rawDescOnce.Do(func() {
		file_certship_v1_certificate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_certship_v1_certificate_proto_rawDesc), len(file_certship_v1_certificate_proto_rawDesc)))
	})
	return file_certship_v1_certificate_proto_rawDescData
}

var file_certship_v1_certificate_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_certship_v1_certificate_proto_goTypes = []any{
	(*ListCertificatesRequest)(nil),       // 0: certship.v1.ListCertificatesRequest
	(*CertificateItem)(nil),               // 1: certship.v1.CertificateItem
	(*SetCertificateManagedRequest)(nil),  // 2: certship.v1.SetCertificateManagedRequest
	(*SetCertificateManagedResponse)(nil), // 3: certship.v1.SetCertificateManagedResponse
	(*DeleteCertificateRequest)(nil),      // 4: certship.v1.DeleteCertificateRequest
	(*DeleteCertificateResponse)(nil),     // 5: certship.v1.DeleteCertificateResponse
	(*ListCertificatesResponse)(nil),      // 6: certship.v1.ListCertificatesResponse
}
var file_certship_v1_certificate_proto_depIdxs = []int32{
	1, // 0: certship.v1.ListCertificatesResponse.certificates:type_name -> certship.v1.CertificateItem
	0, // 1: certship.v1.CertificateService.ListCertificates:input_type -> certship.v1.ListCertificatesRequest
	2, // 2: certship.v1.CertificateService.SetCertificateManaged:input_type -> certship.v1.SetCertificateManagedRequest
	4, // 3: certship.v1.CertificateService.DeleteCertificate:input_type -> certship.v1.DeleteCertificateRequest
	6, // 4: certship.v1.CertificateService.ListCertificates:output_type -> certship.v1.ListCertificatesResponse
	3, // 5: certship.v1.CertificateService.SetCertificateManaged:output_type -> certship.v1.SetCertificateManagedResponse
	5, // 6: certship.v1.CertificateService.DeleteCertificate:output_type -> certship.v1.DeleteCertificateResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_certship_v1_certificate_proto_init() }
func file_certship_v1_certificate_proto_init() {
	if File_certship_v1_certificate_proto != nil {
		return
	}
	file_certship_v1_certificate_proto_msgTypes[0].OneofWrappers = []any{}
	file_certship_v1_certificate_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_certship_v1_certificate_proto_rawDesc), len(file_certship_v1_certificate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_certship_v1_certificate_proto_goTypes,
		DependencyIndexes: file_certship_v1_certificate_proto_depIdxs,
		MessageInfos:      file_certship_v1_certificate_proto_msgTypes,
	}.Build()
	File_certship_v1_certificate_proto = out.File
	file_certship_v1_certificate_proto_goTypes = nil
	file_certship_v1_certificate_proto_depIdxs = nil
}
