// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: certship/v1/renew_task.proto

package certshipv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRenewTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRenewTasksRequest) Reset() {
	*x = ListRenewTasksRequest{}
	mi := &file_certship_v1_renew_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRenewTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRenewTasksRequest) ProtoMessage() {}

func (x *ListRenewTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_renew_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRenewTasksRequest.ProtoReflect.Descriptor instead.
func (*ListRenewTasksRequest) Descriptor() ([]byte, []int) {
	return file_certship_v1_renew_task_proto_rawDescGZIP(), []int{0}
}

type RenewTaskItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domains       []string               `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Trigger       string                 `protobuf:"bytes,4,opt,name=trigger,proto3" json:"trigger,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt     string                 `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    string                 `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewTaskItem) Reset() {
	*x = RenewTaskItem{}
	mi := &file_certship_v1_renew_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewTaskItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewTaskItem) ProtoMessage() {}

func (x *RenewTaskItem) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_renew_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewTaskItem.ProtoReflect.Descriptor instead.
func (*RenewTaskItem) Descriptor() ([]byte, []int) {
	return file_certship_v1_renew_task_proto_rawDescGZIP(), []int{1}
}

func (x *RenewTaskItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenewTaskItem) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *RenewTaskItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RenewTaskItem) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *RenewTaskItem) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RenewTaskItem) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *RenewTaskItem) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *RenewTaskItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListRenewTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*RenewTaskItem       `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRenewTasksResponse) Reset() {
	*x = ListRenewTasksResponse{}
	mi := &file_certship_v1_renew_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRenewTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRenewTasksResponse) ProtoMessage() {}

func (x *ListRenewTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_renew_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRenewTasksResponse.ProtoReflect.Descriptor instead.
func (*ListRenewTasksResponse) Descriptor() ([]byte, []int) {
	return file_certship_v1_renew_task_proto_rawDescGZIP(), []int{2}
}

func (x *ListRenewTasksResponse) GetTasks() []*RenewTaskItem {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CreateRenewTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []string               `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRenewTaskRequest) Reset() {
	*x = CreateRenewTaskRequest{}
	mi := &file_certship_v1_renew_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRenewTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRenewTaskRequest) ProtoMessage() {}

func (x *CreateRenewTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_renew_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRenewTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateRenewTaskRequest) Descriptor() ([]byte, []int) {
	return file_certship_v1_renew_task_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRenewTaskRequest) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type CreateRenewTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRenewTaskResponse) Reset() {
	*x = CreateRenewTaskResponse{}
	mi := &file_certship_v1_renew_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRenewTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRenewTaskResponse) ProtoMessage() {}

func (x *CreateRenewTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certship_v1_renew_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRenewTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateRenewTaskResponse) Descriptor() ([]byte, []int) {
	return file_certship_v1_renew_task_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRenewTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_certship_v1_renew_task_proto protoreflect.FileDescriptor

const file_certship_v1_renew_task_proto_rawDesc = "" +
	"\n" +
	"\x1ccertship/v1/renew_task.proto\x12\vcertship.v1\"\x17\n" +
	"\x15ListRenewTasksRequest\"\xef\x01\n" +
	"\rRenewTaskItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\adomains\x18\x02 \x03(\tR\adomains\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\atrigger\x18\x04 \x01(\tR\atrigger\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\a \x01(\tR\n" +
	"finishedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"J\n" +
	"\x16ListRenewTasksResponse\x120\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1a.certship.v1.RenewTaskItemR\x05tasks\"2\n" +
	"\x16CreateRenewTaskRequest\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains\")\n" +
	"\x17CreateRenewTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xcb\x01\n" +
	"\x10RenewTaskService\x12Y\n" +
	"\x0eListRenewTasks\x12\".certship.v1.ListRenewTasksRequest\x1a#.certship.v1.ListRenewTasksResponse\x12\\\n" +
	"\x0fCreateRenewTask\x12#.certship.v1.CreateRenewTaskRequest\x1a$.certship.v1.CreateRenewTaskResponseB>Z<github.com/solarhell/certship/pkg/api/certship/v1;certshipv1b\x06proto3"

var (
	file_certship_v1_renew_task_proto_rawDescOnce sync.Once
	file_certship_v1_renew_task_proto_rawDescData []byte
)

func file_certship_v1_renew_task_proto_rawDescGZIP() []byte {
	file_certship_v1_renew_task_proto_rawDescOnce.Do(func() {
		file_certship_v1_renew_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_certship_v1_renew_task_proto_rawDesc), len(file_certship_v1_renew_task_proto_rawDesc)))
	})
	return file_certship_v1_renew_task_proto_rawDescData
}

var file_certship_v1_renew_task_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_certship_v1_renew_task_proto_goTypes = []any{
	(*ListRenewTasksRequest)(nil),   // 0: certship.v1.ListRenewTasksRequest
	(*RenewTaskItem)(nil),           // 1: certship.v1.RenewTaskItem
	(*ListRenewTasksResponse)(nil),  // 2: certship.v1.ListRenewTasksResponse
	(*CreateRenewTaskRequest)(nil),  // 3: certship.v1.CreateRenewTaskRequest
	(*CreateRenewTaskResponse)(nil), // 4: certship.v1.CreateRenewTaskResponse
}
var file_certship_v1_renew_task_proto_depIdxs = []int32{
	1, // 0: certship.v1.ListRenewTasksResponse.tasks:type_name -> certship.v1.RenewTaskItem
	0, // 1: certship.v1.RenewTaskService.ListRenewTasks:input_type -> certship.v1.ListRenewTasksRequest
	3, // 2: certship.v1.RenewTaskService.CreateRenewTask:input_type -> certship.v1.CreateRenewTaskRequest
	2, // 3: certship.v1.RenewTaskService.ListRenewTasks:output_type -> certship.v1.ListRenewTasksResponse
	4, // 4: certship.v1.RenewTaskService.CreateRenewTask:output_type -> certship.v1.CreateRenewTaskResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_certship_v1_renew_task_proto_init() }
func file_certship_v1_renew_task_proto_init() {
	if File_certship_v1_renew_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_certship_v1_renew_task_proto_rawDesc), len(file_certship_v1_renew_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_certship_v1_renew_task_proto_goTypes,
		DependencyIndexes: file_certship_v1_renew_task_proto_depIdxs,
		MessageInfos:      file_certship_v1_renew_task_proto_msgTypes,
	}.Build()
	File_certship_v1_renew_task_proto = out.File
	file_certship_v1_renew_task_proto_goTypes = nil
	file_certship_v1_renew_task_proto_depIdxs = nil
}
